### ISSUE TITLE
Listing collections by radicale returns only first collection?

### ISSUE THREAD

**Issue by Phyks** [Kozea/Radicale#377] opened 2016-04-14 10:26 UTC
Hi,

I am using Radicale with DavDroid. Everything works fine with Thunderbird, and I have set up `.well-known` URLs which are working fine as well.

Still, when configuring my server with davdroid, I only get one of my calendars listed, and nothing else (no carddav, no other calendars).

When trying to debug a bit, I have this in Radicale's log:
- First, davdroid does a `PROPFIND` on `/username/` (`base_prefix` is `/`)
- Radicale checks for the rights, and found that `username has read/write access to collection username/` and `username has read/write access to collection username/one_calendar.ics` (where `one_calendar` is the only one I am seeing).
- Response content is (my username is `phyks`, the `one_calendar.ics` shown is `cours.ics`):

```
<?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><resourcetype /><current-user-privilege-set /><displayname /><CARD:addressbook-description /><CARD:supported-address-data /><CAL:calendar-description /><n0:calendar-color xmlns:n0="http://apple.com/ns/ical/" /><CAL:supported-calendar-component-set /></prop></propfind>
```
- Following response content in the log is

```
<?xml version="1.0"?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:CR="urn:ietf:params:xml:ns:carddav" xmlns:ICAL="http://apple.com/ns/ical/">
  <response>
    <href>/phyks/</href>
    <propstat>
      <prop>
        <resourcetype>
          <principal />
          <collection />
        </resourcetype>
        <current-user-privilege-set>
          <privilege>
            <all />
            <read />
            <write />
            <write-properties />
            <write-content />
          </privilege>
        </current-user-privilege-set>
        <displayname>phyks</displayname>
        <ICAL:calendar-color>#662d1a</ICAL:calendar-color>
        <C:supported-calendar-component-set>
          <C:comp name="VTODO" />
          <C:comp name="VEVENT" />
          <C:comp name="VJOURNAL" />
        </C:supported-calendar-component-set>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
      <prop>
        <CR:addressbook-description />
        <CR:supported-address-data />
        <C:calendar-description />
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
  </response>
  <response>
    <href>/phyks/cours.ics/</href>
    <propstat>
      <prop>
        <resourcetype>
          <C:calendar />
          <collection />
        </resourcetype>
        <current-user-privilege-set>
          <privilege>
            <all />
            <read />
            <write />
            <write-properties />
            <write-content />
          </privilege>
        </current-user-privilege-set>
        <displayname>cours.ics</displayname>
        <ICAL:calendar-color>#acfe14</ICAL:calendar-color>
        <C:supported-calendar-component-set>
          <C:comp name="VTODO" />
          <C:comp name="VEVENT" />
          <C:comp name="VJOURNAL" />
        </C:supported-calendar-component-set>
      </prop>
<status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
      <prop>
        <CR:addressbook-description />
        <CR:supported-address-data />
        <C:calendar-description />
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
  </response>
</multistatus>
```

I am using latest version of davdroid (from f-droid) and latest version of radicale installed from `pip`. Let me know if I can provide anymore debug infos.

Thanks a lot!

**Comment by liZe** [comment] 2016-08-01 11:08
@Phyks discovery has changed a lot during the last weeks, could you try the current master branch of Radicale? (You should try with a different folder storing collections as the storage format has changed)

**Comment by Phyks** [comment] 2016-08-01 13:43
I don't have a reliable network connection at the moment, but will be back next week. I test this as soon as possible and will update the issue. Thanks!

**Comment by Phyks** [comment] 2016-08-10 23:35
So I give it a quick try and experiences some issues with `master` branch:

1. I cannot run it any longer with Python 2.7.9. I have:
```
$ python2 radicale.py
  File "radicale.py", line 4
SyntaxError: Non-ASCII character '\xc2' in file radicale.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
2. I had to install `vobject` (maybe it could be useful to have a `requirements.txt` file) dependency to launch it. Afterwards, I have this traceback:
```
$ python3 radicale.py
Traceback (most recent call last):
  File "radicale.py", line 31, in <module>
    radicale.__main__.run()
  File "/root/Radicale/radicale/__main__.py", line 101, in run
    logger = log.start("radicale", filename, debug)
  File "/root/Radicale/radicale/log.py", line 46, in start
    configure_from_file(logger, filename, debug)
  File "/root/Radicale/radicale/log.py", line 33, in configure_from_file
    logging.config.fileConfig(filename)
  File "/usr/lib/python3.4/logging/config.py", line 74, in fileConfig
    cp.read(fname)
  File "/usr/lib/python3.4/configparser.py", line 669, in read
    for filename in filenames:
TypeError: 'Logger' object is not iterable
```

I could not find a way to overcome this by forcing config file and so on. I have this error using Python 3.4.2. I tried to run it from my laptop running Arch, and did not get any error.

I have to go at the moment and will try to find some time to give it a longer try tomorrow.

**Comment by liZe** [comment] 2017-03-04 14:03
The current master branch only supports Python 3.3+, see #372 for more information.

The problem is probably fixed now, I think that we can safely close this issue. Feel free to reopen if needed.

**Closed by liZe** 2017-03-04 14:03 UTC
Labels: bug
