### ISSUE TITLE
Error when syncing calendar after migration to 2.1.8

### ISSUE THREAD

**Issue by ghost** [Kozea/Radicale#758] opened 2017-12-19 12:33 UTC
I recently migrated from 1.x to 2.1.8, following the instructions on http://radicale.org/1to2/. However, now one of my calendars won't sync (several others do sync correctly).

The server-side error:
`ERROR: An exception occurred during PROPFIND request on '/alexander/jobb.ics/': Failed to load item 'anru8fl75lv98n2g1kiqvpfmps_google.com-20150326T162132Z.ics' in 'alexander/jobb.ics': Main component missing`

The client-side error:
https://gist.github.com/ezeenova/c3a39b8e5c2d80d5d8e5a82ca538b530

Any ideas what the problem might be?

**Comment by ezeenova** [comment] 2017-12-19 12:55
--verify-storage turned up several more errors in the same calendar:
`[76dc4010] ERROR: Invalid item 'anru8fl75lv98n2g1kiqvpfmps_google.com-20150326T162132Z.ics' in 'alexander/jobb.ics': Failed to load item 'anru8fl75lv98n2g1kiqvpfmps_google.com-20150326T162132Z.ics' in 'alexander/jobb.ics': Main component missing
[76dc4010] ERROR: Invalid item '20170201T133033Z-2971-1000-1571-19_bela-20170201T133033Z.ics' in 'alexander/jobb.ics': Failed to load item '20170201T133033Z-2971-1000-1571-19_bela-20170201T133033Z.ics' in 'alexander/jobb.ics': Overwritten recurrence with RRULESET
[76dc4010] ERROR: Invalid item '20170201T132238Z-2971-1000-1571-0_bela-20170201T132505Z.ics' in 'alexander/jobb.ics': Failed to load item '20170201T132238Z-2971-1000-1571-0_bela-20170201T132505Z.ics' in 'alexander/jobb.ics': can't compare offset-naive and offset-aware datetimes
[76dc4010] ERROR: Invalid item '20170201T133024Z-2971-1000-1571-18_bela-20170201T133024Z.ics' in 'alexander/jobb.ics': Failed to load item '20170201T133024Z-2971-1000-1571-18_bela-20170201T133024Z.ics' in 'alexander/jobb.ics': Overwritten recurrence with RRULESET
[76dc4010] ERROR: Invalid item '20140306T151406Z-3581-1000-3323-5_debian-20140819T064746Z.ics' in 'alexander/jobb.ics': Failed to load item '20140306T151406Z-3581-1000-3323-5_debian-20140819T064746Z.ics' in 'alexander/jobb.ics': can't compare offset-naive and offset-aware datetimes
[76dc4010] ERROR: Storage verifcation failed`

**Comment by ezeenova** [comment] 2018-01-30 10:32
Well, in my case the problem was easily fixed by removing the offending files manually. Since they were all far in the past this was not a problem. So as far as I am concerned the issue is solved.
I will leave it open in case someone else faces the same problem but cannot feasibly remove the problematic files. Dev, feel free to close if you prefer.

**Comment by akorn** [comment] 2018-07-16 15:29
FWIW, I also have this problem and will likely also just delete the offending entries. Just adding this comment to confirm the bug.

Preferably, 1.x shouldn't export invalid entries, but 2.x should deal with them more gracefully if any are found.

**Comment by pbiering** [comment] 2024-11-24 20:20
please reopen if reproducable with current version

**Closed by pbiering** 2024-11-24 20:20 UTC
Labels: old version
