### ISSUE TITLE
Main Component is missing when only recurrence id exists

### ISSUE THREAD

**Issue by balrok** [Kozea/Radicale#715] opened 2017-09-28 08:00 UTC
I get the exception "Main Component is missing" in 2.1.8. I'm sure in an earlier version maybe 2.1.3 it didn't happen.

The error is here:
https://github.com/Kozea/Radicale/blob/2.1.8/radicale/xmlutils.py#L331

I "fixed" it (not sure if fixed or hacked).
By adding this:

```diff
diff --git a/radicale/xmlutils.py b/radicale/xmlutils.py
index fd9a0d4..b8da5fe 100644
--- a/radicale/xmlutils.py
+++ b/radicale/xmlutils.py
@@ -315,6 +315,7 @@ def _visit_time_ranges(vobject_item, child_name, range_fn, infinity_fn):

     def get_children(components):
         main = None
+        rec_main = None
         recurrences = []
         for comp in components:
             if hasattr(comp, "recurrence_id") and comp.recurrence_id.value:
@@ -322,11 +323,14 @@ def _visit_time_ranges(vobject_item, child_name, range_fn, infinity_fn):
                 if comp.rruleset:
                     # Prevent possible infinite loop
                     raise ValueError("Overwritten recurrence with RRULESET")
+                rec_main = comp
                 yield comp, True, ()
             else:
                 if main is not None:
                     raise ValueError("Multiple main components")
                 main = comp
+        if main is None and len(recurrences) == 1:
+            main = rec_main
         if main is None:
             raise ValueError("Main component missing")
         yield main, False, recurrences
```

**Comment by Unrud** [comment] 2017-10-05 16:44
Sounds like this is a duplicate of #700.
The main component, shouldn't contain the ``RECURRENCE-ID`` line.

**Comment by emdete** [comment] 2017-12-05 13:48
i got that too it seems. i received an ical from a outlook server which could not be inserted with the very same error. i removed the line mentioned in #700 and everything worked fine. maybe it's good to have a fix even when the ical is broken?

**Comment by Unrud** [comment] 2017-12-06 17:28
> i received an ical from a outlook server which could not be inserted with the very same error.

Can you provide a sample file?

**Comment by Unrud** [comment] 2017-12-06 17:30
> i received an ical from a outlook server which could not be inserted with the very same error.

Can you provide a sample file?

**Comment by emdete** [comment] 2017-12-07 14:26
sure, i hope i didn't destroy it by anonomysing it:

```
BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:GTB Standard Time
BEGIN:STANDARD
DTSTART:16010101T040000
TZOFFSETFROM:+0300
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0300
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ORGANIZER;CN="Bar Foo";SENT-BY="MAILTO:org@foo.bar":MAILTO:bar@ffo.org
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN="Bar Foo":MAILTO:bar@foo.org
DESCRIPTION;LANGUAGE=en-US:..............................\n\n\n
SUMMARY;LANGUAGE=en-US:FW: Summary
DTSTART;TZID=GTB Standard Time:20171208T141500
DTEND;TZID=GTB Standard Time:20171208T150000
UID:999999999999999999999999999999999999999
RECURRENCE-ID;TZID=GTB Standard Time:20171207T150000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20171207T112236Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:13
LOCATION;LANGUAGE=en-US:Skype Meeting
X-MICROSOFT-CDO-APPT-SEQUENCE:13
X-MICROSOFT-CDO-OWNERAPPTID:0000000000
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DISALLOW-COUNTER:FALSE
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:-PT15M
END:VALARM
END:VEVENT
END:VCALENDAR
```

**Comment by Jereviendrai** [comment] 2018-08-14 13:43
I am getting the same error after upgrading from version 1.1.16 to 2.1.9. When requesting PROPFIND of the affected collection I get this in the log (the request returns error 500):
```
2018-08-14 15:22:17,996 - ERROR: An exception occurred during PROPFIND request on '/user/': Failed to load item 'f5diowcksu345hs6fh5msr20180409T150000@google.com' in 'user/calendar.ics': Main component missing
```
This calendar was originally exported from Google Calendar and heavily uses recurring events. 

I also tried re-importing it into radicale directly (using curl) from the .ics I exported from Google Calendar, which also gives me 
```
2018-08-14 15:28:47,076 - WARNING: Bad PUT request on '/alinea/bkpr.ics': Failed to store item 'df9a9298-977e-e2b9-09d4-d76309f983cc.ics' in temporary collection 'alinea/bkpr.ics': Main component missing
```
Is there any update or workaround for this?

For reference this is one of the broken items in the collection:
```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:user@example.com
X-WR-TIMEZONE:Europe/Zurich
BEGIN:VTIMEZONE
TZID:Europe/Zurich
X-LIC-LOCATION:Europe/Zurich
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
X-RADICALE-NAME:Europe/Zurich
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
X-RADICALE-NAME:Europe/Zurich
END:STANDARD
X-RADICALE-NAME:Europe/Zurich
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=Europe/Zurich:20180522T170000
DTEND;TZID=Europe/Zurich:20180522T180000
DTSTAMP:20180814T130704Z
ORGANIZER;CN=Stand-Up and Townhall Meetings:mailto:example.com_ddddddddddddddddddddddd@group.calendar.google.com
UID:f5afvgce1elj3g1p4rp2ccl5msr20180409T150000@google.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=Team EMEA;X-NUM-GUESTS=0:mailto:team-emea@example.com
ATTENDEE;CUTYPE=RESOURCE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=BKPR-WW-Office Buzz;X-NUM-GUESTS=0:mailto:example.com_66666666666666666@resource.calendar.google.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=user@example.com;X-NUM-GUESTS=0:mailto:user@example.com
ATTENDEE;CUTYPE=RESOURCE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Common area;X-NUM-GUESTS=0:mailto:example.com_32333333333333333333333@resource.calendar.google.com
ATTENDEE;CUTYPE=RESOURCE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN="(Common Area)-Zurich HQ-3-Hive (99) [Dual-Screen, Speakerphone]";X-NUM-GUESTS=0:mailto:example.com_666666666666666666666@resource.calendar.google.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=anon@example.com;X-NUM-GUESTS=0:mailto:anon@example.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=Team USA;X-NUM-GUESTS=0:mailto:team-usa@example.com
RECURRENCE-ID;TZID=Europe/Zurich:20180521T170000
CREATED:20180515T161432Z
DESCRIPTION:removed
LAST-MODIFIED:20180603T133903Z
LOCATION:Common Area
SEQUENCE:4
STATUS:CONFIRMED
SUMMARY:Team Meeting
TRANSP:OPAQUE
X-RADICALE-NAME:f5afvgce1elj3g1p4rp2ccl5msr20180409T150000@google.com
END:VEVENT
END:VCALENDAR
```

**Comment by Notmarrco** [comment] 2018-12-13 08:03
Thank you @balrok , for the "fix" or "hack" !!

I had the same error, and at first I tried to remove the "RECURRENCE-ID" lines, but after that I got "Multiple main components" error.

With your fix it works ok. 
NB : I was trying to import a Google Calendar like @Jereviendrai .

**Comment by mck182** [comment] 2021-01-15 20:12
I'm still unable to fully import Google Calendar ics files with Radicale 3.0.6 - it fails with "Main component missing" exception:
```
[2021-01-15 14:43:20 -0500] [18635/Thread-99] [WARNING] Bad PUT request on '/cal/9840d1b5-5b4d-585b-7a13-cc0235ef8401/fec9c42a0d4401ebf02791383be9cc0656526bf391a9e87c297d551d54a5a7cb.ics': Main component missing
Traceback (most recent call last):
  File "/home/cal/.local/lib/python3.7/site-packages/radicale/app/put.py", line 85, in prepare
    item.prepare()
  File "/home/cal/.local/lib/python3.7/site-packages/radicale/item/__init__.py", line 394, in prepare
    self.time_range
  File "/home/cal/.local/lib/python3.7/site-packages/radicale/item/__init__.py", line 384, in time_range
    find_tag_and_time_range(self.vobject_item))
  File "/home/cal/.local/lib/python3.7/site-packages/radicale/item/__init__.py", line 262, in find_tag_and_time_range
    radicale_filter.visit_time_ranges(vobject_item, tag, range_fn, infinity_fn)
  File "/home/cal/.local/lib/python3.7/site-packages/radicale/item/filter.py", line 235, in visit_time_ranges
    vobject_item.vevent_list):
  File "/home/cal/.local/lib/python3.7/site-packages/radicale/item/filter.py", line 229, in get_children
    raise ValueError("Main component missing")
```

Here's one of the files it fails with.
[Google Calendar ics file](https://github.com/Kozea/Radicale/files/5822704/broken.txt)

The fix by @balrok at the top does not fix this particular issue. Please let me know if I can help further!

**Comment by IvanCharcos** [comment] 2021-02-21 20:58
Getting this issue as well. Doesnt seem like there is a fix.

**Comment by lambdaupb** [comment] 2021-05-17 01:11
Same Issue on debian (2.1.11-6) buster with a migrated dataset from an older 1.1 version.

Patch worked.

**Comment by NiklasRosenstein** [comment] 2021-07-13 22:15
I'm getting the same issue on Radicale 3.0.6 after trying to upload an .ics from Nextcloud.

**Comment by fcorneli** [comment] 2021-07-28 06:38
Same issue over here when trying to upload my calendar in Radicale.
```
[2021-07-28 06:31:27 +0000] [13141/Thread-9] [ERROR] '(UTC+01:00) Brussel, Kopenhagen, Madrid, Parijs'
[2021-07-28 06:31:27 +0000] [13141/Thread-9] [ERROR] '(UTC+01:00) Brussel, Kopenhagen, Madrid, Parijs'
[2021-07-28 06:31:27 +0000] [13141/Thread-9] [ERROR] '(UTC+00:00) Dublin, Edinburgh, Lisbon, London'
[2021-07-28 06:31:27 +0000] [13141/Thread-9] [ERROR] '(UTC+00:00) Dublin, Edinburgh, Lisbon, London'
[2021-07-28 06:31:27 +0000] [13141/Thread-9] [ERROR] '(UTC+01:00) Brussel, Kopenhagen, Madrid, Parijs'
[2021-07-28 06:31:27 +0000] [13141/Thread-9] [ERROR] '(UTC+01:00) Brussel, Kopenhagen, Madrid, Parijs'
[2021-07-28 06:31:27 +0000] [13141/Thread-9] [DEBUG] Rule 'fcorneli':'fcorneli' doesn't match '.+':'' from section 'root'
[2021-07-28 06:31:27 +0000] [13141/Thread-9] [DEBUG] Rule 'fcorneli':'fcorneli' matches '.+':'{user}' from section 'principal'
[2021-07-28 06:31:28 +0000] [13141/Thread-9] [ERROR] '(UTC+01:00) Brussel, Kopenhagen, Madrid, Parijs'
[2021-07-28 06:31:28 +0000] [13141/Thread-9] [ERROR] '(UTC+01:00) Brussel, Kopenhagen, Madrid, Parijs'
[2021-07-28 06:31:28 +0000] [13141/Thread-9] [ERROR] '(UTC+00:00) Dublin, Edinburgh, Lisbon, London'
[2021-07-28 06:31:28 +0000] [13141/Thread-9] [ERROR] '(UTC+00:00) Dublin, Edinburgh, Lisbon, London'
[2021-07-28 06:31:30 +0000] [13141/Thread-9] [WARNING] Bad PUT request on '/fcorneli/cf8e7878-96f6-0432-2b75-7418e047bfa8/': Main component missing
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/radicale/app/put.py", line 73, in prepare
    item.prepare()
  File "/usr/local/lib64/python3.6/site-packages/radicale/item/__init__.py", line 394, in prepare
    self.time_range
  File "/usr/local/lib64/python3.6/site-packages/radicale/item/__init__.py", line 384, in time_range
    find_tag_and_time_range(self.vobject_item))
  File "/usr/local/lib64/python3.6/site-packages/radicale/item/__init__.py", line 262, in find_tag_and_time_range
    radicale_filter.visit_time_ranges(vobject_item, tag, range_fn, infinity_fn)
  File "/usr/local/lib64/python3.6/site-packages/radicale/item/filter.py", line 231, in visit_time_ranges
    vobject_item.vevent_list):
  File "/usr/local/lib64/python3.6/site-packages/radicale/item/filter.py", line 225, in get_children
    raise ValueError("Main component missing")
ValueError: Main component missing
[2021-07-28 06:31:30 +0000] [13141/Thread-9] [DEBUG] Response content:
Bad Request
[2021-07-28 06:31:30 +0000] [13141/Thread-9] [INFO] PUT response status for '/fcorneli/cf8e7878-96f6-0432-2b75-7418e047bfa8/' in 3.620 seconds: 400 Bad Request
```

**Comment by tonioo** [comment] 2021-12-14 08:57
The provided patch works for me on Radicale 3.0.6 but it should be applied against the ``item/filter.py`` file, the ``get_children`` method is located there now.

**Comment by pSub** [comment] 2022-07-09 20:41
I've encountered this error when importing a ics from Outlook / OWA. The anonymized version of the ics file is:

```
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
X-WR-CALNAME:Kalender
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:040000008200E00074C5B7101A82E00800000000E476CE672288D601000000000000000
 0100000007DC39D71BC6C4542B067F66FE2CA2B71
RECURRENCE-ID;TZID=W. Europe Standard Time:20220422T000000
SUMMARY:Jour Six
DTSTART;TZID=W. Europe Standard Time:20220422T103000
DTEND;TZID=W. Europe Standard Time:20220422T113000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20220706T221100Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:17
LOCATION:sixvice
X-MICROSOFT-CDO-APPT-SEQUENCE:17
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
END:VCALENDAR
```
Is there any reason the fix mentioned in the issue description is not applied?

**Comment by fcorneli** [comment] 2023-10-26 06:04
Any reason why this merge stalls?

**Closed** 2024-03-01 05:24 UTC
Labels: bug, needs reporter feedback
