### ISSUE TITLE
RuntimeError: Failed to find tag and time range of item / can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by lpirl** [Kozea/Radicale#632] opened 2017-06-08 07:38 UTC
just got this trace when syncing the entire calendar using Lightning:
<pre>
[7fe71d995700] ERROR: An exception occurred during request: Failed to find tag and time range of item '21620938-e30e-41ee-ad22-1d9fa67c9db9.ics' from 'lukas/cal': can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/storage.py", line 1023, in _get_with_metadata
    vobject_item)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 605, in find_tag_and_time_range
    _visit_time_ranges(vobject_item, tag, range_fn, infinity_fn)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 303, in _visit_time_ranges
    dtstarts = child.getrruleset(addRDate=True)
  File "/home/lukas/.local/lib/python3.5/site-packages/vobject/icalendar.py", line 501, in getrruleset
    if rruleset._rrule[-1][0] != adddtstart:
  File "/home/lukas/.local/lib/python3.5/site-packages/dateutil/rrule.py", line 159, in __getitem__
    res = advance_iterator(gen)
  File "/home/lukas/.local/lib/python3.5/site-packages/dateutil/rrule.py", line 860, in _iter
    if until and res > until:
TypeError: can't compare offset-naive and offset-aware datetimes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/__init__.py", line 300, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/__init__.py", line 462, in _handle_request
    environ, base_prefix, path, user)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/__init__.py", line 721, in do_PROPFIND
    base_prefix, path, xml_content, read_items, write_items, user)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 733, in propfind
    base_prefix, path, collection, props, user, write=True)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 914, in _propfind_response
    element.text = item.etag
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/storage.py", line 1217, in etag
    for item in self.get_all():
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/storage.py", line 1073, in <genexpr>
    return (self.get(href, verify_href=False) for href in self.list())
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/storage.py", line 969, in get
    item, metadata = self._get_with_metadata(href, verify_href=verify_href)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/storage.py", line 1027, in _get_with_metadata
    e)) from e
RuntimeError: Failed to find tag and time range of item '21620938-e30e-41ee-ad22-1d9fa67c9db9.ics' from 'lukas/cal': can't compare offset-naive and offset-aware datetimes
</pre>

The corresponding event looks like this:

<pre>
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
BEGIN:VEVENT
UID:21620938-e30e-41ee-ad22-1d9fa67c9db9
DTSTART;VALUE=DATE:20150401
DTEND;VALUE=DATE:20150402
CREATED:20150327T122628Z
DTSTAMP:20150831T121458Z
LAST-MODIFIED:20150831T121458Z
RRULE:FREQ=MONTHLY;UNTIL=20150901T110000Z
STATUS:CONFIRMED
SUMMARY:--removed--
TRANSP:TRANSPARENT
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Default Event Notification
TRIGGER:PT0S
X-WR-ALARMUID:74ffebb3-4c86-4881-95fa-94f64553006f
END:VALARM
X-MOZ-GENERATION:3
X-MOZ-LASTACK:20150831T121107Z
END:VEVENT
END:VCALENDAR
</pre>

**Comment by Unrud** [comment] 2017-06-09 01:05
It's a bug in [VObject](http://eventable.github.io/vobject/). I implemented a workaround, it should work now.

You will still get WARNING messages:

```
[7fa09bc3b700] WARNING: Failed to find tag and time range of item '21620938-e30e-41ee-ad22-1d9fa67c9db9.ics' from 'lukas/cal' (Bug in VObject): failed to call getrruleset: can't compare offset-naive and offset-aware datetimes
[7fa09bc3b700] WARNING: Failed to filter item '21620938-e30e-41ee-ad22-1d9fa67c9db9.ics' from 'lukas/cal' (Bug in VObject): failed to call getrruleset: can't compare offset-naive and offset-aware datetimes
```

I close this, because it's a duplicate of #602.

**Closed by Unrud** 2017-06-09 01:05 UTC

**Comment by lpirl** [comment] 2017-06-09 07:05
Thanks a lot @Unrud. Just to be sure: did you expect a warning and a trace?
<pre>
[7f7a4bf75700] WARNING: Failed to find tag and time range of item '2625cdbc-b6aa-437f-bd62-ae62bb659725.ics' from 'lukas/cal' (Bug in VObject): empty iterator from getrruleset
Traceback (most recent call last):
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/storage.py", line 1047, in _get_with_metadata
    vobject_item)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 620, in find_tag_and_time_range
    _visit_time_ranges(vobject_item, tag, range_fn, infinity_fn)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 320, in _visit_time_ranges
    dtstarts, infinity = getrruleset(child)
  File "/home/lukas/.local/lib/python3.5/site-packages/radicale/xmlutils.py", line 305, in getrruleset
    "empty iterator from getrruleset")
radicale.xmlutils.VObjectBugException: empty iterator from getrruleset
[7f7a4bf75700] WARNING: Failed to find tag and time range of item '867da68f-a7c3-4202-879c-b8638c03dbb7.ics' from 'lukas/cal' (Bug in VObject): empty iterator from getrruleset
</pre>

**Comment by Unrud** [comment] 2017-06-09 12:17
> did you expect a warning

Yes.

> and a trace?

You get the trace, because debugging is enabled.

**Comment by lpirl** [comment] 2017-06-09 12:18
Alright, just wanted to make sure this wasn't another issue.
