### ISSUE TITLE
ValueError: unsupported DTSTART parm: VALUE=DATE-TIME

### ISSUE THREAD

**Issue by potuz** [Kozea/Radicale#646] opened 2017-06-22 23:50 UTC
This seems to be more of an issue with python-dateutil module than radicale, but nonetheless I report here in search for help. When trying to sync a calendar built from khal/vdirsyncer I get 

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/vobject/base.py", line 183, in transformToNati
ve
    return self.behavior.transformToNative(self)
  File "/usr/lib/python3.4/site-packages/vobject/icalendar.py", line 989, in transformT
oNative
    obj.registerTzinfo(obj.tzinfo)
  File "/usr/lib/python3.4/site-packages/vobject/icalendar.py", line 150, in gettzinfo
    return tz.tzical(buffer).get()
  File "/usr/lib/python3.4/site-packages/dateutil/tz/tz.py", line 1109, in __init__
    self._parse_rfc(fobj.read())
  File "/usr/lib/python3.4/site-packages/dateutil/tz/tz.py", line 1230, in _parse_rfc
    cache=True)
  File "/usr/lib/python3.4/site-packages/dateutil/rrule.py", line 1603, in __call__
    return self._parse_rfc(s, **kwargs)
  File "/usr/lib/python3.4/site-packages/dateutil/rrule.py", line 1562, in _parse_rfc
    raise ValueError("unsupported DTSTART parm: "+parm)
ValueError: unsupported DTSTART parm: VALUE=DATE-TIME

Which is due to rrule.py not wanting any parameter to DTSTART. Can I do something about this?

**Comment by Unrud** [comment] 2017-08-06 11:22
This can be closed when https://github.com/dateutil/dateutil/pull/429 gets merged.

**Comment by doofy** [comment] 2018-01-31 16:07
dateutil/dateutil#429 is merged so we can close this right?

**Comment by DmitrySandalov** [comment] 2018-03-20 23:49
khal/vdirsyncer seems to be working, no exception with
python-dateutil==2.7.0
Radicale==2.1.8

**Comment by jalr** [comment] 2018-06-10 16:59
as @DmitrySandalov already mentioned, Radicale 2.1.8 and python-dateutil 2.7.0 works but if I upgrade to Radicale 2.1.9 I get the message ```radicale 2.1.9 has requirement python-dateutil==2.6.1, but you'll have python-dateutil 2.7.3 which is incompatible.``` and it doesn't work
I'm also using vdirsyncer so it seems that I'm stuck on 2.1.8 for now.

**Comment by pbiering** [comment] 2024-10-01 19:41
please try with up-to-date radicale and vobject and reopen depending on root cause

**Closed by pbiering** 2024-10-01 19:41 UTC
Labels: dependency:vobject, old version, not our bug
