### ISSUE TITLE
Cannot connect to existing VCard file

### ISSUE THREAD

**Issue by flusi100** [Kozea/Radicale#352] opened 2016-01-20 04:49 UTC
I use radicale to keep my calendar, tasts and contacts synced mainly between my mobile devices with DAVDroid and CalDAV-/CardDAV-Sync.

If you enter a URL with a non existing vcf, it is automatically created and syncs well thereafter with mobile client. But I cannot connect a device to an existing vcf-file.

This problem occours on both clients, DAVDroid and CardDAV-Sync.

Which additional details do I have to provide?

**Comment by flusi100** [comment] 2016-01-20 05:31
Supplement: Although I enter the path including the vcf file, DAVDroid lets me sync on this file as calendar and tasks (behaviour of an ics file).
When I enter the path to the vcf file in a browser, an ics file is downloaded, with the content of the vcf.

**Comment by flusi100** [comment] 2016-01-20 05:59
Here is a log from CardFAV-Sync.
[20160120.errorlog.txt](https://github.com/Kozea/Radicale/files/97007/20160120.errorlog.txt)

**Comment by liZe** [comment] 2016-03-14 18:12
Hi,

Thank you for your report, sorry for taking this time to answer…

Radicale cannot work with an existing file put in the calendars storage folder. You must use a client to put the calendar with a PUT HTTP request (`curl` knows how to send PUT request for example). You just have to PUT the whole calendar at `http://myaddress/user/mycalendar.ics/`.

**Comment by liZe** [comment] 2016-04-17 05:08
@flusi100 did you try this solution?

**Comment by Unrud** [comment] 2017-06-09 21:46
I close this, because it's the expected behavior.

**Closed by Unrud** 2017-06-09 21:46 UTC
