### ISSUE TITLE
TypeError: initial_value must be unicode or None, not str

### ISSUE THREAD

**Issue by prplmnky** [Kozea/Radicale#333] opened 2015-11-22 02:48 UTC
I'm getting the following error whenever I request a calendar URL.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python2.7/dist-packages/radicale/__init__.py", line 312, in __call__
    self.collect_allowed_items(items, user)
  File "/usr/lib/python2.7/dist-packages/radicale/__init__.py", line 195, in collect_allowed_items
    if rights.authorized(user, item, "r"):
  File "/usr/lib/python2.7/dist-packages/radicale/rights/regex.py", line 111, in authorized
    _read_from_sections(user or "", collection_url, permission))
  File "/usr/lib/python2.7/dist-packages/radicale/rights/regex.py", line 72, in _read_from_sections
    regex.readfp(StringIO(DEFINED_RIGHTS[rights_type]))
TypeError: initial_value must be unicode or None, not str
```

The following code fixes the error, although I'm not a Python guy so there may be better ways.
`radicale/rights/regex.py`  Line 72: `regex.readfp(StringIO(unicode(DEFINED_RIGHTS[rights_type])))`

I'm running version 0.10-2

**Comment by liZe** [comment] 2015-11-22 16:08
Your issue is a duplicate of #282, it's fixed since 1.0. If you can't update Radicale, you'll find a solution to fix the problem in the issue comments.

**Closed by liZe** 2015-11-22 16:08 UTC
