### ISSUE TITLE
Support Firefox OS calender

### ISSUE THREAD

**Issue by brutus** [Kozea/Radicale#271] opened 2015-03-18 15:05 UTC
I'm using **Firefox OS** on my mobile. Their calender app has *CalDav* support and it worked with my [Baikal](http://baikal-server.com/) server. I switch to Radicale because of the nice access rights management. Works swell with Thunderbird+Lightning but bails on Firefox OS.

Any hints on how to fix this? Or any workarounds? 

The error message I get is frustratingly un–helpful: *"unknown error. try again later."*. Running radicale with `--debug` yields nothing, so the request might be malformed?

**Comment by hobarrera** [comment] 2015-05-09 18:14
I wanted to do some debugging on this to see if I could provide any info for you or the devs.
I configured Firefox OS's calendar to use my calendar at URL `https://calendar.barrera.io/hugo/work/`. This is the server's output:

```
PROPFIND request at /hugo/calendar.ics/ received
Request headers:
{'CONTENT_LENGTH': '351',
 'CONTENT_TYPE': 'text/xml; charset=UTF-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_AUTHORIZATION': 'Basic REDACTED',
 'HTTP_CONNECTION': 'close',
 'HTTP_DEPTH': '1',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Mobile; rv:39.0) Gecko/20100101 Firefox/39.0',
 'PATH_INFO': '/hugo/calendar.ics/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': 'localhost',
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'elysion.barrera.io',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.9',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x74635da1e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x741f62fb48>,
 'wsgi.input': <socket._fileobject object at 0x74790cac50>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
Sanitized path: /hugo/calendar.ics/
Request content:
<?xml version="1.0" encoding="UTF-8"?><N2:propfind xmlns:N0="http://apple.com/ns/ical/
" xmlns:N1="urn:ietf:params:xml:ns:caldav" xmlns:N2="DAV:" xmlns:N3="http://calendarse
rver.org/ns/"><N2:prop><N0:calendar-color /><N1:calendar-description /><N2:current-use
r-privilege-set /><N2:displayname /><N2:resourcetype /><N3:getctag /></N2:prop></N2:pr
opfind>
Rights type 'owner_only'
Test if 'hugo:hugo/calendar.ics' matches against '.+:^hugo(/.*)?$' from section 'rw'
Section 'rw' matches
hugo has read access to collection hugo/calendar.ics/
Rights type 'owner_only'
Test if 'hugo:hugo/calendar.ics' matches against '.+:^hugo(/.*)?$' from section 'rw'
Section 'rw' matches
hugo has write access to collection hugo/calendar.ics/
Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://cal
endarserver.org/ns/" xmlns:ICAL="http://apple.com/ns/ical/">
  <response>
    <href>/hugo/calendar.ics/</href>
    <propstat>
      <prop>
        <ICAL:calendar-color>#695756</ICAL:calendar-color>
        <current-user-privilege-set>
          <privilege>
            <all />
            <read />
            <write />
            <write-properties />
            <write-content />
          </privilege>
        </current-user-privilege-set>
        <displayname>calendar.ics</displayname>
        <resourcetype>
          <C:calendar />
          <collection />
        </resourcetype>
        <CS:getctag>"d41d8cd98f00b204e9800998ecf8427e"</CS:getctag>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
      <prop>
        <C:calendar-description />
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
  </response>
</multistatus>

Answer status: 207 Unknown
```

I may be wrong here, but the request for `/hugo/calendar.ics/` (see first line of output) seems wrong: the calendar is at `/hugo/work/`.  I may be mistaken here, but IMHO, firefox is doing the wrong request.

Downloading the same calendar with another program does not exhibit a similar behaviour.

**Comment by liZe** [comment] 2016-03-14 18:28
@brutus @hobarrera Can we consider FirefoxOS client as dead :crying_cat_face:?

**Comment by hobarrera** [comment] 2016-03-14 18:31
I personally don't care much about FirefoxOS support anymore, but I still wonder if this is triggered by a yet-unfound radicale bug or not.
I'm hesitant to close the issue until we make sure there's nothing broken on radicale's side.

**Comment by liZe** [comment] 2016-03-14 18:40
Radicale doesn't follow the specification [by design](http://radicale.org/technical_choices/#idoriented-to-calendar-and-contact-user-agents). The problem seems to be related to the way this client finds the collection according to the URL given in its configuration, so you can safely close this bug if you didn't meet this bug with another client.

**Comment by liZe** [comment] 2016-04-18 07:02
With FirefoxOS being discontinued for smartphones, I think that I can safely close this bug (unless someone wants to try the current master branch).

**Closed by liZe** 2016-04-18 07:02 UTC
Labels: feature
