### ISSUE TITLE
Radicale changing .ics file

### ISSUE THREAD

**Issue by Gregmee** [Kozea/Radicale#697] opened 2017-09-04 13:25 UTC
Have finally updated to Radicale 2.1.5 from version 1.XX

We have .ics files that meets .ics standards but radicale 2.1.5 is changing the .ics files and moving the calendar name and TTL to the end of the file (which outlook doesn't like) and is also truncating the description field of the ics file so that the full description isn't shown.

Is there a way to turn off the parsing and changing of the .ics file in 2.1.5?

Thanks

**Comment by Unrud** [comment] 2017-09-04 15:19
Can you provide an example file?

``DESCRIPTION`` isn't truncated, but it's split into multiple lines. Maybe Outlook doesn't understand that.
I don't know what you mean by "calendar name" and "TTL".

The calendar objects are parsed and serialized by [VObject](https://github.com/eventable/vobject/).

> Is there a way to turn off the parsing and changing of the .ics file in 2.1.5?

No.

**Comment by Gregmee** [comment] 2017-09-05 04:33
![3](https://user-images.githubusercontent.com/16306914/30045188-3d719de4-9235-11e7-9de5-c121a7dbd158.JPG)
[ics.zip](https://github.com/Kozea/Radicale/files/1276059/ics.zip)
![2](https://user-images.githubusercontent.com/16306914/30045189-3d775c70-9235-11e7-98cc-aefdc02f2eea.JPG)
![1](https://user-images.githubusercontent.com/16306914/30045190-3d7a7392-9235-11e7-9f3c-3ea15b448c97.JPG)

Hi. Abbreviated original file that sits on server (orig.ics) and one delivered by Radicale (radicale.ics) attached.

Images 1 and 3 show you where timezone,calendar name and TTL (how oftern device should check in for updates) are at top of file in original.ics but moved to the bottom in radicale.ics. Outlook 2016 doesn't seem to pick up the calendar name if it's at the bottom of the file.

Image 2 shows what's happening in the description field. We have a list of the crew that our users will be flying with in the description field however you can see in the right hand side only the first part of the description field is being delivered by Radicale. It appears once it gets to a comma stops processing the description field.

Thanks
Greg

**Comment by Unrud** [comment] 2017-09-05 17:44
> Images 1 and 3 show you where timezone,calendar name and TTL (how oftern device should check in for updates) are at top of file in original.ics but moved to the bottom in radicale.ics.

I reported the problem to https://github.com/eventable/vobject/issues/94. The iCalendar specification only recommends specifying all properties prior to components. Technically the file is still valid and Outlook should be able to find the calendar name and TTL.

> It appears once it gets to a comma stops processing the description field.

The comma is used as the list separator. If it appears in normal text, it must be escaped ``\,``. VObject only keeps the first list entry. This seems to be a bug in your client.

> radicale.ics

Have you disabled error checking of calendar components? Otherwise, I don't understand how Radicale could even produce a file like ``radicale.ics``.

Radicale is primarily a CalDAV/CardDAV server, which also kind of supports publishing calendars via WebDAV.
If you are only using Radicale to publish calendars via WebDAV from Outlook and download them via HTTP, I think you are better off using a normal HTTP server with modules for WebDAV (e.g. Apache or nginx).

**Comment by Unrud** [comment] 2017-09-27 17:42
The issue is fixed in VObject. Additionally, Radicale imports the calendar name and description from X-WR-CALNAME and X-WR-CALDESC, when a calendar is published via WebDAV. When a whole calendar is downloaded, it writes the calendar name and description in X-WR-CALNAME and X-WR-CALDESC.

**Closed by Unrud** 2017-09-27 17:42 UTC
Labels: bug, not our bug, VObject
