### ISSUE TITLE
radicale upload VCARD2.1 failed

### ISSUE THREAD

**Issue by osnosn** [Kozea/Radicale#1238] opened 2022-04-25 07:13 UTC
In debian11, `apt install radicate` installed radicate-3.0.6.

when I upload a VCF file via browser, it failed.

This is the VCF file:   
```
BEGIN:VCARD
VERSION:2.1
N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;=E6=B5=8B=E8=AF=95=E6=B5=8B=E8=AF=95=E6=B5=8B=E8=AF=95=E6=B5=8B=E8=AF=
=95=E6=B5=8B=E8=AF=95=E6=B5=8B;;;
FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=E6=B5=8B=E8=AF=95=E6=B5=8B=E8=AF=95=E6=B5=8B=E8=AF=95=E6=B5=8B=E8=AF=
=95=E6=B5=8B=E8=AF=95=E6=B5=8B
TEL;CELL:12 345 678 90
PHOTO;ENCODING=BASE64;JPEG:/9j/4AAQS....
 2wBDAQcHBwo....

END:VCARD
``` 

------

I changed VCF file, then upload OK.   
* change QUOTED-PRINTABLE in one line.
* change PHOTO:ENCODING=BASE64; to PHOTO:ENCODING=B; 
```
BEGIN:VCARD
VERSION:2.1
N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;=E6=B5=8B=E8=AF=95=E6=B5=8B=E8=AF=95=E6=B5=8B=E8=AF=95=E6=B5=8B=E8=AF=95=E6=B5=8B=E8=AF=95=E6=B5=8B;;;
FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=E6=B5=8B=E8=AF=95=E6=B5=8B=E8=AF=95=E6=B5=8B=E8=AF=95=E6=B5=8B=E8=AF=95=E6=B5=8B=E8=AF=95=E6=B5=8B
TEL;CELL:12 345 678 90
PHOTO;ENCODING=B;JPEG:/9j/4AAQS....
 2wBDAQcHBwo....

END:VCARD
```

**Comment by Barugon** [comment] 2022-11-10 20:23
I've been trying to upload my contacts (vCard 3.0) and I get the same thing.

**Comment by slyduda** [comment] 2022-12-15 04:05
I was able to fix this by commenting the following lines from the vobject package `vcard.py` file 

```py
    def decode(cls, line):
        """
        Remove backslash escaping from line.valueDecode line, either to remove
        backslash espacing, or to decode base64 encoding. The content line should
        contain a ENCODING=b for base64 encoding, but Apple Addressbook seems to
        export a singleton parameter of 'BASE64', which does not match the 3.0
        vCard spec. If we encouter that, then we transform the parameter to
        ENCODING=b
        """
        if line.encoded:
            if 'BASE64' in line.singletonparams:
                line.singletonparams.remove('BASE64')
                line.encoding_param = cls.base64string
            encoding = getattr(line, 'encoding_param', None)
            if encoding:
                if isinstance(line.value, bytes):
                    line.value = codecs.decode(line.value, "base64")
#                else:
#                    line.value = codecs.decode(line.value.encode("utf-8"), "base64")
            else:
                line.value = stringToTextValues(line.value)[0]
            line.encoded = False
```

The encoding gets all wonky when BASE64 is used for the encoding param. I am not sure why and I am sure this quick fix breaks other cases, but it allows me to use base64 encoding on photos now so that's all that matters for me.

**Comment by pbiering** [comment] 2022-12-15 06:38
"radicale" depends in this case 100% on vobject -> one has to wait until "vobject" got proper fixed

**Comment by da4089** [comment] 2024-03-02 22:18
I have constructed an example vCard, using the first quoted template above, and current vObject parses it without any problem.

The code segment above _is_ a little dubious, in several ways, but ... for data that is properly BASE64 encoded, the encoding of the string value to bytes will change nothing (since BASE64 is pure ASCII, and pure ASCII encoded as UTF-8 is byte-wise identical).

It'd be great if one of the reporters (@osnosn, @Fijxu, @quamok, @slyduda) could provide the Radicale log file showing one of these failed imports -- it'd be really useful to see exactly _how_ it's failing.

**Comment by yangtfu** [comment] 2024-04-25 05:22
> I have constructed an example vCard, using the first quoted template above, and current vObject parses it without any problem.
> 
> The code segment above _is_ a little dubious, in several ways, but ... for data that is properly BASE64 encoded, the encoding of the string value to bytes will change nothing (since BASE64 is pure ASCII, and pure ASCII encoded as UTF-8 is byte-wise identical).
> 
> It'd be great if one of the reporters (@osnosn, @Fijxu, @quamok, @slyduda) could provide the Radicale log file showing one of these failed imports -- it'd be really useful to see exactly _how_ it's failing.

```[2024-04-25 13:20:54 +0800] [141563/Thread-18 (process_request_thread)] [WARNING] Bad PUT request on '/ytf/f17655c9-2159-bae2-e297-cd403db8cb31/': At line 159: Failed to parse line: =30=34=33=33=3F=E9=97=AA=E9=97=AA=48=E7=BA=A2=E6=98=9F
Traceback (most recent call last):
  File "/home/ytf/ws/py_ws/Radicale/radicale/app/put.py", line 145, in do_PUT
    vobject_items = radicale_item.read_components(content or "")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ytf/ws/py_ws/Radicale/radicale/item/__init__.py", line 52, in read_components
    return list(vobject.readComponents(s))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ytf/anaconda3/envs/radi/lib/python3.12/site-packages/vobject/base.py", line 1101, in readComponents
    vline = textLineToContentLine(line, n)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ytf/anaconda3/envs/radi/lib/python3.12/site-packages/vobject/base.py", line 925, in textLineToContentLine
    return ContentLine(*parseLine(text, n), **{'encoded': True,
                        ^^^^^^^^^^^^^^^^^^
  File "/home/ytf/anaconda3/envs/radi/lib/python3.12/site-packages/vobject/base.py", line 813, in parseLine
    raise ParseError("Failed to parse line: {0!s}".format(line), lineNumber)
vobject.base.ParseError: At line 159: Failed to parse line: =30=34=33=33=3F=E9=97=AA=E9=97=AA=48=E7=BA=A2=E6=98=9F
[2024-04-25 13:20:54 +0800] [141563/Thread-18 (process_request_thread)] [DEBUG] Response content:
Bad Request
[2024-04-25 13:20:54 +0800] [141563/Thread-18 (process_request_thread)] [INFO] PUT response status for '/ytf//f17655c9-2159-bae2-e297-cd403db8cb31/' in 0.090 seconds: 400 Bad Request
```

**Comment by pbiering** [comment] 2024-04-25 05:38
Is this special vcard passing the validator without any errors? Please check with https://icalendar.org/validator.html
But even if it's the case, as one see, it's related to `vobject`.

**Comment by da4089** [comment] 2024-04-25 08:44
Thanks for the further info, @yangtfu!

The line that reports a parsing problem:

    "=30=34=33=33=3F=E9=97=AA=E9=97=AA=48=E7=BA=A2=E6=98=9F"

run through `base64.b64decode()`, ends up being:

    b'\xdfM\xf8\xdf}\xf7\xdcQ=\xf7\xb0\x00\x13\xdf{\x00\x0e<\x13\xb0@\x03a:\xf7\xcfE'

which ... doesn't look like it'd be a valid vCard line.  It's not valid UTF-8 either.  So I'm not sure what it's trying to do.

Could you please copy the whole problematic vCard into a comment?  Maybe it's a continuation line or something ...  With the complete input, hopefully we can figure this out.

**Comment by da4089** [comment] 2024-04-25 23:05
I've run into a couple of issues testing that card.

First, it's missing the `BEGIN:VCARD` at the start.  Perhaps that's just a cut-and-paste error?  If not, then the encoder is pretty broken, and I'm not sure what could be done about parsing it.

Next, if I add a `BEGIN:VCARD` to the start, it is parsed successfully using Python 3.7 and current vObject.

Last, the problematic string `=30=34=33=33=3F=E9=97=AA=E9=97=AA=48=E7=BA=A2=E6=98=9F` from the previous report doesn't seem to be in this card at all.  Can you please check that this is card that's causing the exception?

**Comment by yangtfu** [comment] 2024-04-26 01:47
@da4089 It's a paste error. The file is quite long. I'll put it [here](https://gist.githubusercontent.com/yangtfu/414e6efa2b2b0535e973ee831cf0aa75/raw/e5746d41ef6d476d85782b86f3be1e0d8b9f3660/contact.vcf)

**Comment by da4089** [comment] 2024-04-27 14:28
Thanks @yangtfu, that's very helpful.

I am able to reproduce the problem.  @pbiering, the problem is here:

```
  File "/home/ytf/ws/py_ws/Radicale/radicale/item/__init__.py", line 52, in read_components
    return list(vobject.readComponents(s))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

If that's changed to `return list(vobject.readComponents(s, allowQP=True)` the sample file is processed correctly in my test case code.  I'm not across the history of why allowing quoted-printable encoding is disabled by default in _vobject_, but I think this will likely be a frequent source of problems for those whose cards use non-ASCII characters encoded for vCard 2.1 (which required 7-bit clean data).

I'm also unaware of any past issues this might have had in Radicale: perhaps it's disabled for a reason here?

Either way, I've sent a PR (#1476) with the above change.  It's had no testing in Radicale.

**Comment by pbiering** [comment] 2024-04-27 14:56
Thank you for tracing down the issue.

> I'm also unaware of any past issues this might have had in Radicale: perhaps it's disabled for a reason here?

Potentially nobody so far was aware about.

> Either way, I've sent a PR (#1476) with the above change. It's had no testing in Radicale.

Can you create a 2nd PR with extending the test cases?

**Comment by pbiering** [comment] 2024-04-27 15:18
PR merged, please test.

Once test case is added, this PR can be closed.

**Closed** 2024-05-03 05:32 UTC
Labels: VObject, improvement
