### ISSUE TITLE
2.0.0rc2 does not create calendars from Thunderbird Lightning like 1.1.1

### ISSUE THREAD

**Issue by vlapla** [Kozea/Radicale#582] opened 2017-04-22 19:51 UTC
With the server running and a user with authentication set up I got 404 errors in the debug log, and no proper synchronisation in Thunderbird, trying to add events. Adding a new event would add a file in [storage-filesystem-folder]/[username], but Thunderbird was not able to read it from there. Only after I created [calendarname.ics] on the server with mkdir, I got a working calendar.

I know the documentation for 2.0.0 is yet to be updated/ written, but is this intended behaviour?

I never really used Radicale 1.1.1, but as a test I also ran it on my local (Ubuntu) machine, and there connecting to a calendar via Thunderbird would cause Radicale to simply create the necessary files.

Currently migrating my self-hosted calendar(s) from OwnCloud on a RaspberryPi to Radicale on a router (Netgear WNDR3700v2) running LEDE (an OpenWRT fork). So I decided to give the 2.0.0rc2 a try directly, since it seems to be quite an improvement over version 1.1.1.

After the Thunderbird test I also successfully connected my phone running Android 6 (LineageOS) with DAVdroid. It seems like I've now got a super-minimalistic calendar server running. Merci beaucoup, liZe!

**Comment by vlapla** [comment] 2017-04-22 19:56
Hmm, reading the comment from @Unrud on #579 it seems like this is a Thunderbird issue... but it certainly is a case for the documentation too.

**Comment by vlapla** [comment] 2017-04-28 07:04
Slightly off topic: I wrote I was using Radicale 2.0 on my router running LEDE... but that only worked for a test setup, with less than 10 events. When I tried importing my actual calendar with more than 100 events, it took more than 100 seconds (maybe even more than 200, I forgot the exact DEBUG output) to synchronise... leading to my clients not synchronising at all. Radicale, and even LEDE, would also crash occasionally, probably due to insufficient memory. So I'm back to running the calendar on the RaspberryPi (now with double port forwarding), and for now it is just Radicale 1.1.1. Version 2.0.0rc2 would not run out of the box on my Raspbian 9 system. But I feel like I already invested way too much time in setting up my calendar server, so I'll stop experimenting, and just wait for version 2 to be included in Debian/ Raspbian. rc1 is already in 'experimental' now.

**Comment by Unrud** [comment] 2017-04-28 08:06
Radicale uses a lot of memory. Take a look at this benchmark: https://github.com/Kozea/Radicale/pull/569#issuecomment-295955540

That PR fixes most of the speed and memory problems. REPORT requests still require too much memory (~20MiB for 10.000 items). It should be quiet easy to fix, but I'm waiting until that PR gets merged by @liZe.

**Comment by Unrud** [comment] 2017-06-09 21:48
I close this, because it's the expected behavior. The development version of Radicale has a web interface for creating address book and calendars. The speed and memory usage issues are also resolved.

**Closed by Unrud** 2017-06-09 21:48 UTC
