### ISSUE TITLE
Address family not supported by protocol

### ISSUE THREAD

**Issue by flabbafan** [Kozea/Radicale#1054] opened 2020-05-24 13:26 UTC
After upgrading to Radicale 3 on Arch Linux (package in the official repository) the server will not start, spitting the error in the title. On my machine ipv6 is disabled in the kernel and after investigating it seems that this error can be related to the lack of ipv6 support. Is ipv6 required for Radicale 3? I've been running Radicale 2 very happily for months.
Here is a snippet of the logs:

May 24 09:14:21 prospe radicale[1199]: [2020-05-24 09:14:21 -0400] [1199] [INFO] Loaded default config
May 24 09:14:21 prospe radicale[1199]: [2020-05-24 09:14:21 -0400] [1199] [INFO] Loaded config file '/etc/radicale/config'
May 24 09:14:21 prospe radicale[1199]: [2020-05-24 09:14:21 -0400] [1199] [INFO] Skipped missing config file '/.config/radicale/config'
May 24 09:14:21 prospe radicale[1199]: [2020-05-24 09:14:21 -0400] [1199] [INFO] Starting Radicale
May 24 09:14:21 prospe radicale[1199]: [2020-05-24 09:14:21 -0400] [1199] [INFO] auth type is 'radicale.auth.htpasswd'
May 24 09:14:21 prospe radicale[1199]: [2020-05-24 09:14:21 -0400] [1199] [INFO] storage type is 'radicale.storage.multifilesystem'
May 24 09:14:21 prospe radicale[1199]: [2020-05-24 09:14:21 -0400] [1199] [INFO] rights type is 'radicale.rights.owner_only'
May 24 09:14:21 prospe radicale[1199]: [2020-05-24 09:14:21 -0400] [1199] [INFO] web type is 'radicale.web.internal'
May 24 09:14:21 prospe radicale[1199]: [2020-05-24 09:14:21 -0400] [1199] [INFO] Listening on '[0.0.0.0]:5233' with SSL
May 24 09:14:21 prospe radicale[1199]: [2020-05-24 09:14:21 -0400] [1199] [CRITICAL] An exception occurred during server startup: Failed to start server '[0.0.0.0]:5233': [Errno 97] Address family not supported by protocol
May 24 09:14:21 prospe radicale[1199]: Traceback (most recent call last):
May 24 09:14:21 prospe radicale[1199]:   File "/usr/lib/python3.8/site-packages/radicale/server.py", line 223, in serve
May 24 09:14:21 prospe radicale[1199]:     server = server_class(configuration, family, address,
May 24 09:14:21 prospe radicale[1199]:   File "/usr/lib/python3.8/site-packages/radicale/server.py", line 68, in __init__
May 24 09:14:21 prospe radicale[1199]:     super().__init__(address, RequestHandlerClass)
May 24 09:14:21 prospe radicale[1199]:   File "/usr/lib/python3.8/socketserver.py", line 448, in __init__
May 24 09:14:21 prospe radicale[1199]:     self.socket = socket.socket(self.address_family,
May 24 09:14:21 prospe radicale[1199]:   File "/usr/lib/python3.8/socket.py", line 231, in __init__
May 24 09:14:21 prospe radicale[1199]:     _socket.socket.__init__(self, family, type, proto, fileno)
May 24 09:14:21 prospe radicale[1199]: OSError: [Errno 97] Address family not supported by protocol
May 24 09:14:21 prospe radicale[1199]: The above exception was the direct cause of the following exception:
May 24 09:14:21 prospe radicale[1199]: Traceback (most recent call last):
May 24 09:14:21 prospe radicale[1199]:   File "/usr/lib/python3.8/site-packages/radicale/__main__.py", line 150, in run
May 24 09:14:21 prospe radicale[1199]:     server.serve(configuration, shutdown_socket_out)
May 24 09:14:21 prospe radicale[1199]:   File "/usr/lib/python3.8/site-packages/radicale/server.py", line 243, in serve
May 24 09:14:21 prospe radicale[1199]:     raise RuntimeError("Failed to start server %r: %s" % (
May 24 09:14:21 prospe radicale[1199]: RuntimeError: Failed to start server '[0.0.0.0]:5233': [Errno 97] Address family not supported by protocol

In the config file I have only configured one ipv4 host:
hosts = 0.0.0.0:5233

Thanks!

**Comment by Unrud** [comment] 2020-05-24 13:40
Fixed in version 3.0.2.

Duplicate of #1050

**Closed by Unrud** 2020-05-24 13:40 UTC
