### ISSUE TITLE
Config file is missing

### ISSUE THREAD

**Issue by dannycolin89** [Kozea/Radicale#592] opened 2017-05-16 22:12 UTC
When I install Radicale with PIP, the config file doesn't seem to be created. I don't have that problem if I install it with my package manager. I'm on Ubuntu 16.04.2.

**Comment by htgoebel** [comment] 2017-05-26 09:52
pip is a packet manager for python packages, not for system packages. pip has no notion about where to put config-files, how to start programs at boot time, etc. Such kind of things is out of scope for pip.

**Comment by liZe** [comment] 2017-05-26 12:17
@htgoebel is right, you have to create your configuration file, pip won't install it for you. The way configuration files are created and updated is managed by your distribution / your OS / you, not by the package manager. It's not a bug of pip, it's a feature :wink:.

**Closed by liZe** 2017-05-26 12:17 UTC

**Comment by dannycolin89** [comment] 2017-05-29 01:00
Oh I didn't kown that. Thanks for the answer :)
