### ISSUE TITLE
Radical does show other user's resources

### ISSUE THREAD

**Issue by htgoebel** [Kozea/Radicale#593] opened 2017-05-19 17:07 UTC
Radical does show other user's resources, it does even search for other's resources.

This is quite un-handly, since so one needs to add several accounts, e.g "own", "family", "public" just to be able to access all the collections.

### How to reproduce:
0. Setup:
```
pyvenv /tmp/radicale
cd /tmp/radicale
. /tmp/radicale/bin/activate
pip install passlib bcrypt radicale
# copy the simple `config` file and `rights` file (see below).
mkdir -p var/lib/radicale/collections/maxmustermann
mkdir -p var/lib/radicale/collections/public
```
1. start radicale under strace `strace -f -e trace=file -o /tmp/trace.txt racale --config=etc/radicale/config`
2. On some android device use davdroid,  create a now davdroid account for the redicale server and some user (e.g. `http://radicale-server:5232/maxmustemann` with user `maxmustermann`).
3. "Rescan calendars" for this davdroid account.
4. Stop redicale
5. `grep lib/radicale/collections /tmp/trace.txt`
   You will only see filesystem-calls to `lib/radicale/collections/maxmustermann`.

### What I'd expect
1. radicale should report all collections accessible by the user, not only those within his/her prefix
2. radicale should at least *scan* for other resources – which means instep 5 above there should be syscalls to find other collections, e.g. `openat`.

#### config
[auth]
type = htpasswd
htpasswd_filename = /tmp/radicale/etc/radicale/users
htpasswd_encryption = plain
[rights]
type = from_file
file = /tmp/radicale/etc/radicale/rights
[storage]
filesystem_folder = /tmp/radicale/var/lib/radicale/collections
#### /tmp/radicale/etc/radicale/rights
[public]
user: .+
collection: ^public
permission: r
[virtual]
user: .+
collection: ^%(login)s
permission: rw
#### /tmp/radicale/etc/radicale/users
maxmustermann:test1234

**Comment by Unrud** [comment] 2017-06-09 20:53
I close this, because It's the expected behavior. Calendar sharing is not (yet) supported by Radicale.

**Closed by Unrud** 2017-06-09 20:53 UTC
