### ISSUE TITLE
REGRESSION 2.1.10: cannot create new calendar since commit 546a52e

### ISSUE THREAD

**Issue by mandree** [Kozea/Radicale#977] opened 2019-08-01 12:20 UTC
Since radiCALe 2.1.10, I can no longer create new calendars, no matter if I used DAVx⁵ on Android or the Radicale web interface. This has been working in 2.1.9. I am using the owner_only rights backend, but this appears unrelated to rights as shown below.

I have `git bisect`ed this down to an individual commit, the first bad commit is:
[546a52e34a42f8556644067bd09b18c78b31f878] Improve HTTP status codes

The failure-inducing commit contains this hunk, and the final `if ...` check bails out because `parent_item.get_meta("tag")` returns `"VCALENDAR"`. I have added a debug statement and got this:
`[7fd7fb405700] DEBUG: do_MKCOL_2: parent_item=<radicale.storage.load.<locals>.CollectionCopy object at 0x7fd7fbb3a1d0>, storage.BaseCollection=<class 'radicale.storage.BaseCollection'>, isinstance(...)=True, meta_tag=VCALENDAR`

This is the offending hunk of the failure-inducing commit.

**Removing the `or parent_item.get_meta("tag")` restores the create-new-calendar function.**

```
@@ -644,7 +661,16 @@ class Application:
         with self.Collection.acquire_lock("w", user):
             item = next(self.Collection.discover(path), None)
             if item:
-                return WEBDAV_PRECONDITION_FAILED
+                return self._webdav_error_response(
+                    "D", "resource-must-be-null")
+            parent_path = storage.sanitize_path(
+                "/%s/" % posixpath.dirname(path.strip("/")))
+            parent_item = next(self.Collection.discover(parent_path), None)
+            if not parent_item:
+                return CONFLICT
+            if (not isinstance(parent_item, storage.BaseCollection) or
+                    parent_item.get_meta("tag")):
+                return FORBIDDEN
```

**Comment by Unrud** [comment] 2020-01-16 06:46
It's a feature not a bug. Radicale 2.1.10 got new checks too make sure you can't create a invalid collection structures or upload items to collections they are not supposed to be.

To me it looks like you storage already contains errors. You have to run ``radicale --verify-storage`` and fix the errors manually.

**Comment by mandree** [comment] 2020-01-16 16:26
On both computers where I run radicale, `radicale --verify-storage` returns without any output. And if what you most recent comment is saying is true, both the commit log as well as the NEWS.md are pretty insufficient.

**Comment by Unrud** [comment] 2020-01-17 14:29
> both the commit log as well as the NEWS.md are pretty insufficient.

Right, I guess "Improve HTTP status codes" is insufficient.

> ``radicale --verify-storage`` returns without any output.

Sorry, the check I was thinking of is only in master.

Your storage folder contains a directory ``/collection-root/USERNAME``.
The web interface and DAVx5 try to create a new address book collection in the folder ``/collection-root/USERNAME/RANDOM_NAME``.
This fails because the collection ``/collection-root/USERNAME`` is marked as a calendar. WebDAV forbids address book and calendar collections to have child collections.

To fix this make sure that the folder ``/collection-root/USERNAME`` does not contain any event files and then remove the key ``"tag"`` from the JSON file ``/collection-root/USERNAME/.Radicale.props``.

**Comment by mandree** [comment] 2020-01-17 16:13
OK, understood & done, so how did that tag get there in the first place? Incomplete migration from 1.x? Broken DAV client? (Lightning, SOGOConnector, Cardbook, DAVx⁵, ...) (and apparently I had to destroy and recreate the account in DAVx⁵ to get rid of that calendar named USERNAME - re-scanning for calendars did not fix it.)

And it would GREATLY help if that fact could not just `return FORBIDDEN` but also log the real reason, in a verbose description saying that I am trying to nest calendars, which is not permitted.

**Closed** 2020-05-19 15:30 UTC
