### ISSUE TITLE
Events not shown on google calendar and thunderbird.

### ISSUE THREAD

**Issue by maniackcrudelis** [Kozea/Radicale#401] opened 2016-05-20 21:57 UTC
On google calendar and thunderbird (and probably other programs), some events are not displayed.
The log of radicale does not indicate any error.

But searching the .ics files, I noticed that the events do not appear have the same uid as other events. After analysis, several events with the same uid, only one is displayed.

I think that the events that share the same uid are duplicated and modified events at the time of their creation.

-------------------

Sur google calendar et thunderbird (et probablement d'autres clients), certains évènements ne sont pas affichés.
Le log de radicale n'indique aucune erreur.

Mais en fouillant les fichiers ics, j'ai remarqué que les évènements non affichés ont le même uid que d'autres évènements. Après analyse, sur plusieurs évènements ayant le même uid, seul un seul est affiché.

Je pense que les évènements partageant le même uid sont des évènements dupliqués puis modifiés au moment de leur création.

**Comment by liZe** [comment] 2016-05-21 16:12
Yes, the UID and the path of the event are related in the current stable version, and it leads to a lot of bugs, including duplicated UIDs leading to missing events. It's a bug "by design" and there's no easy fix possible for 1.1.x.

It's now fixed in current master (and will be available in 2.x).

**Closed by liZe** 2016-05-21 16:12 UTC

**Comment by maniackcrudelis** [comment] 2016-05-21 16:40
OK
And the master is stable and usable?

**Comment by liZe** [comment] 2016-05-21 16:49
No, unfortunately it's not. You can follow the ticket #372 to know what's remaining before 2.0.
