### ISSUE TITLE
Update client documentation for Gnome Evolution

### ISSUE THREAD

**Issue by dilyanpalauzov** [Kozea/Radicale#1074] opened 2020-06-30 18:31 UTC
Please update the information at https://radicale.org/master.html#documentation/supported-clients about Gnome/Evolution. Users shall create one 'Collection account' and it will contain all addreeabooks and calendars.

**Comment by ialokim** [comment] 2020-07-08 22:11
I tried to add my Radicale account in Evolution using the 'Collection account', but I was not able to do so. Is there any special trick needed to get it working?

Btw, this is a duplicate of #1057.

**Comment by dilyanpalauzov** [comment] 2020-07-09 05:35
It should work without special tricks.

**Comment by ialokim** [comment] 2020-07-09 08:55
Just for the record, Evolution seems to have a bug when using e-mail addresses as usernames: Instead of sending the whole e-mail address, it removes the domain and therefore authorization is not possible. I'll probably open an issue over there.

**Comment by dilyanpalauzov** [comment] 2020-07-09 09:25
This was addressed in https://gitlab.gnome.org/GNOME/evolution/-/issues/610#note_598801 .

**Comment by ialokim** [comment] 2020-07-09 09:28
Wow, true, I'm still using an older version. Thank you very much!

**Closed** 2024-03-02 12:28 UTC
