### ISSUE TITLE
Crashes eventually if disconnected from the internet

### ISSUE THREAD

**Issue by infinity0** [Kozea/Radicale#1313] opened 2023-06-23 19:32 UTC
Radicale tries to resolve its own server hostnames at startup, bypassing the C standard library functions (`getaddrinfo` etc) which first check `/etc/hosts`, and instead going straight to DNS. This fails to resolve `localhost` - the default value from Radicale's configs - when disconnected from the internet, causing Radicale to crash and quit.

This is problematic for servers on unreliable home networks, especially those that are on a long restart loop - such as Debian's Radicale, whose logrotate configuration will restart Radicale every week. If Radicale is disconnected from the internet during a restart, it will fail and not be restarted for another week, even if internet access comes back up in the meantime.

The fix is extremely simple, namely to use `getaddrinfo(1)` (whatever the Python equivalent is) - the same as common system utilities such as `ping(1)` and `getent hosts`, which both can resolve `localhost` even when disconnected from the internet.

**Comment by pbiering** [comment] 2024-03-02 12:21
@infinity0 : can you reproduce with 3.1.8? If not, please close

I've cannot replicate the issue, tested by adjusting config to

```
[server]
hosts = localhost2:5232
```

and /etc/hosts extended with:

```
127.0.0.1   localhost2
```

and it's starting without problems:

```
radicale[4026]: [4026] [INFO] Listening on '[127.0.0.1]:5232'
```

**Comment by infinity0** [comment] 2024-03-11 15:33
I'm using Debian radicale 3.1.8 and the bug still exists. Forget about "localhost2", try actually disconnecting from the internet.

I may not have been precisely correct in deducing the root cause of the bug in my description, but the actual symptom still exists. You need to actually disconnect from the internet to see it.

**Comment by pbiering** [comment] 2024-03-11 17:14
I cannot reproduce this on Fedora with a from Internet disconnected system having only `lo` interface.

Following more or less default settings are active, please compare with your system:

```
ip addr show dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
```

```
grep hosts: /etc/nsswitch.conf
hosts:      files mdns4_minimal [NOTFOUND=return] dns myhostname
```
```
cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

```
getent -s files hosts localhost
::1             localhost localhost.localdomain localhost6 localhost6.localdomain6
```

**Comment by infinity0** [comment] 2024-03-11 20:38
Still reproducing on Debian. Only radicale is affected, other services e.g. lighttpd are fine. journal has lines like:

~~~~
Mar 11 20:32:50 <host> radicale[903270]: [2024-03-11 20:32:50 +0000] [903270] [CRITICAL] An exception occurred during server startup: Failed to start server '[localhost]:5232': [Errno 16] Device or resource busy
[..]
Mar 11 20:34:24 <host> radicale[904407]: [2024-03-11 20:34:24 +0000] [904407] [CRITICAL] An exception occurred during server startup: Failed to start server '[localhost]:5232': [Errno -3] Temporary failure in name resolution
~~~~

My system config:

~~~~
# ip addr show dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever

# grep hosts: /etc/nsswitch.conf
hosts:          files mdns4_minimal [NOTFOUND=return] dns

# cat /etc/hosts
127.0.0.1	localhost
[..]

# The following lines are desirable for IPv6 capable hosts
::1	ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters

# getent -s files hosts localhost
127.0.0.1       localhost
~~~~

I tried changing nsswitch.conf to include "myhostname", like yours, with no effect.

I also tried setting `net.ipv6.bindv6only = 1` or `0` plus `sysctl -p` to reload it, also with no effect.

Not sure if `noprefixroute` on my inet6 interface matters - but again, other services are fine, only radicale is failing.

**Comment by infinity0** [comment] 2024-03-11 20:42
BTW the problem has persisted across hardware changes. I recently changed to a new motherboard & everything else, keeping only the hard drive running the OS software the same. The problem has existed with both the new and old hardware, so it's not an issue with my network card or anything like that.

**Comment by infinity0** [comment] 2024-03-11 20:47
I just tried `ip link set <my ethernet card> down` and the problem still persists.

Maybe you could try finding a machine with an ethernet card and actual internet that can be taken down, not just an "Internet disconnected system having only `lo` interface", and see if you can reproduce it that way.

**Comment by infinity0** [comment] 2024-03-11 20:52
Debian patches on top of 3.1.8 are here: https://sources.debian.org/src/radicale/3.1.8-4/debian/patches/

Some of these look network-related, but are just pulling in commits already applied here since 3.1.8.

**Comment by infinity0** [comment] 2024-03-11 21:03
~~~~
# system is offline, ethernet disconnected

# cat /etc/resolv.conf 
# Generated by NetworkManager
[ i.e. empty ]


# systemctl edit radicale
Successfully installed edited file '/etc/systemd/system/radicale.service.d/override.conf'.

# cat /etc/systemd/system/radicale.service.d/override.conf
[Unit]
Wants=network-online.target
After=network-online.target

# systemctl restart radicale
[ wait a few seconds ]

# systemctl status radicale
× radicale.service - A simple CalDAV (calendar) and CardDAV (contact) server
     Loaded: loaded (/usr/lib/systemd/system/radicale.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/radicale.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Mon 2024-03-11 21:02:08 GMT; 1s ago
   Duration: 261ms
       Docs: man:radicale(1)
    Process: 935195 ExecStart=/usr/bin/radicale (code=exited, status=1/FAILURE)
   Main PID: 935195 (code=exited, status=1/FAILURE)
        CPU: 259ms

Mar 11 21:02:08 <host> systemd[1]: radicale.service: Scheduled restart job, restart counter is at 5.
Mar 11 21:02:08 <host> systemd[1]: radicale.service: Start request repeated too quickly.
Mar 11 21:02:08 <host> systemd[1]: radicale.service: Failed with result 'exit-code'.
Mar 11 21:02:08 <host> systemd[1]: Failed to start radicale.service - A simple CalDAV (calendar) and CardDAV (contact) server.
~~~~

**Comment by infinity0** [comment] 2024-03-11 21:05
I think possibly network-online is only relevant during boot, not normal system operation.

**Comment by pbiering** [comment] 2024-03-12 04:49
I still can't reproduce and found a small difference between Enterprise/Fedora Linux and your system:

```
grep localhost /etc/hosts
# For historical reasons, localhost precedes localhost.localdomain:
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

Your system is not resolving `localhost` to an IPv6 address using "files":

```
grep localhost /etc/hosts
127.0.0.1	localhost
::1	ip6-localhost ip6-loopback
```

Is this still "Debian" default content of `/etc/hosts` or wasn't this adjusted during the upgrades in the past? Entries with prefix `ip6-` l looking somehow outdated. Please check by e.g. installing current version on a VM for latest defaults.

BTW: 

> Only radicale is affected, other services e.g. lighttpd are fine.

I would assume, that "lighttpd" is not using binding to "localhost" but "any", therefore not an issue here.

**Comment by infinity0** [comment] 2024-03-12 10:59
> Your system is not resolving `localhost` to an IPv6 address using "files"

It should not be a problem to do this, ever, on any system. If radicale assumes "localhost" can be IPv6, that is its problem, and the source of this bug. If my system tells radicale that localhost is IPv4 only, radicale should not be trying to listen on a IPv6 socket.

**Comment by infinity0** [comment] 2024-03-12 14:51
I can reproduce this problem on my new Linux Mint installation if I **both** stop `systemd-resolved`,  and also edit `/etc/nsswitch.conf` to remove `myhostname`. Doing either one in isolation is not enough to reproduce.

Plain Debian with no derivatives, packages systemd-resolved in a [separate optional package](https://packages.debian.org/sid/systemd-resolved), and it is not a required part of the system. Note: the Debian installer process might install it - I haven't run this for years - but users can easily remove it, and this is a supported behaviour. **Systemd-resolved is not a required part of the system.**

By contrast, Ubuntu, which Linux Mint is based on, includes systemd-resolved as part of their [required systemd package](https://packages.ubuntu.com/jammy/amd64/systemd/filelist). I guess this is the case for Fedora.

However you should be able to stop `systemd-resolved` at least temporarily to reproduce this bug, as well as edit `/etc/nsswitch.conf`.

In any case this is a problem with radicale, not my system configuration. Everything else works fine, it's only radicale that assumes systemd-resolved or its behaviour. Very likely this relates to the localhost -> ipv4+6 behaviour that we were just talking about. This is part of the advertised behaviour of systemd-resolved, see its man page, but it is **not** the behaviour of GNU/Linux in general, including Debian.

**Comment by pbiering** [comment] 2024-03-12 17:09
thank you for all the hints, finally reproduced, will analyse now.

**Comment by pbiering** [comment] 2024-03-12 18:46
fixed by https://github.com/Kozea/Radicale/pull/1430

**Comment by pbiering** [comment] 2024-03-13 04:45
and improved with https://github.com/Kozea/Radicale/pull/1431

@infinity0 : please confirm and close if finally solved

**Comment by infinity0** [comment] 2024-03-13 10:40
That is not the correct fix. You could have done that "fix" back in [my earlier comment](https://github.com/Kozea/Radicale/issues/1313#issuecomment-1989401882), without forcing me to jump through all the hoops to figure out the actual problem. And it would still have been the wrong fix, because it does not solve the actual problem. Please respect the time I spent to actually figure out what the problem is for you, and fix the problem properly.

The actual problem is that Radicale is trying to connect to an IPv6 address when the system explicitly tells Radicale that it's not an IPv6 address - https://github.com/pbiering/Radicale/blob/39c339638d87cc6c114fac96402109d3724a6884/radicale/server.py#L288

The correct solution is to resolve the addresses provided in the configuration (e.g. localhost:5232) into a bunch of addresses, using the same mechanism that the system gives you. Then determine the correct address family AF_INET or AF_INET6 from those addresses, without hardcoding both in advance.

Also in general the surrounding code looks overcomplicated for what one needs to do, I've never seen application code that needs to do all of that. This is a code smell and is probably a side-effect consequence of incorrectly hardcoding in both AF_INET, AF_INET6.

Furthermore your fix is wrong when there is an actual problem, e.g. if the user selects a non-localhost address and this fails to resolve, then you *can't* ignore the error code.

**Comment by pbiering** [comment] 2024-03-13 20:08
I'm not the author of the original code and tried to fix your reported circumstances (btw. you are the only one so far) by an minimal invasive patch.

> Furthermore your fix is wrong when there is an actual problem, e.g. if the user selects a non-localhost address and this fails to resolve, then you can't ignore the error code.

I think this statement is not matching the existing code: `if ((bind_ok or not is_last) and (` will prevent this.

Nevertheless, I will try to rework that part.

**Comment by pbiering** [comment] 2024-03-13 21:41
Code reworked, please give a try: https://github.com/Kozea/Radicale/issues/1313

**Comment by infinity0** [comment] 2024-03-15 10:58
Thanks a lot, the new code looks good to me. One potential issue is if something tries to be "too clever" in the `server_class` function, but the new code as written in that PR looks good. I will try to find some time to test it locally soon, but it's reasonable to assume it should work generally.

**Comment by infinity0** [comment] 2024-03-15 11:04
One nit, I'm not sure how strict your code style standards are for this project, but it is a bit unusual generally to name variables in python using Uppercase even though it is possible, because it looks like a class name.

**Comment by pbiering** [comment] 2024-03-16 06:30
> One potential issue is if something tries to be "too clever" in the `server_class` function

Can't see any issue here beside that in case of listen on IPv6 address that this is not accepting IPv4 requests, which would be in principle possible in case of `[::]`. But introducing an additional option to change this behavior to save one item in the `hosts` config will confuse existing installations and causing an issue then.

```
    def server_bind(self) -> None:
        if self.address_family == socket.AF_INET6:
            # Only allow IPv6 connections to the IPv6 socket
            self.socket.setsockopt(COMPAT_IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)
        super().server_bind()
```

**Comment by pbiering** [comment] 2024-03-16 17:31
@infinity0 : would be great if you can test until tomorrow as this is the last blocker for releasing 3.1.9

**Comment by infinity0** [comment] 2024-03-17 19:15
Just tested on Linux Mint, it works! :tada:

**Comment by pbiering** [comment] 2024-03-18 04:32
thank you very much for testing and patience.

**Closed by pbiering** 2024-03-18 04:32 UTC
Labels: bug, needs reporter feedback
