### ISSUE TITLE
(IntegrityError) insert or update on table "collection" violates foreign key constraint "collection_parent_path_fkey"

### ISSUE THREAD

**Issue by paulepanter** [Kozea/Radicale#219] opened 2014-10-15 13:53 UTC
With Radicale 0.9 [from Debian Sid/unstable](https://packages.debian.org/sid/radicale) and running it with Python 3.4 (Python 3.4.2rc1+), I get the error below. PostgreSQL is used and the schema created with `psql -h postgresql -f /usr/share/radicale/schema.sql radicale radicale`.

        # python3 /usr/bin/radicale -C /etc/radicale/config --ssl
        Traceback (most recent call last):
          File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
            self.result = application(self.environ, self.start_response)
          File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 306, in __call__
            user)
          File "/usr/lib/python3/dist-packages/radicale/__init__.py", line 565, in put
            new_item = collection.get_item(item_name)
          File "/usr/lib/python3/dist-packages/radicale/ical.py", line 354, in get_item
            for item in self.items:
          File "/usr/lib/python3/dist-packages/radicale/storage/database.py", line 264, in items
            (ical.Event, ical.Todo, ical.Journal, ical.Card, ical.Timezone))
          File "/usr/lib/python3/dist-packages/radicale/storage/database.py", line 119, in _query
            .order_by(DBItem.name).all())
          File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2300, in all
            return list(self)
          File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2411, in __iter__
            self.session._autoflush()
          File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1208, in _autoflush
            util.raise_from_cause(e)
          File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
            reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
          File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 182, in reraise
            raise value
          File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1198, in _autoflush
            self.flush()
          File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1919, in flush
            self._flush(objects)
          File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2037, in _flush
            transaction.rollback(_capture_exception=True)
          File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
            compat.reraise(exc_type, exc_value, exc_tb)
          File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 182, in reraise
            raise value
          File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2001, in _flush
            flush_context.execute()
          File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
            rec.execute(self)
          File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
            uow
          File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
            mapper, table, insert)
          File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 570, in _emit_insert_statements
            execute(statement, multiparams)
          File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
            return meth(self, multiparams, params)
          File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
            return connection._execute_clauseelement(self, multiparams, params)
          File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
            compiled_sql, distilled_params
          File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
            context)
          File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
            exc_info
          File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
            reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
          File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 181, in reraise
            raise value.with_traceback(tb)
          File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
            context)
          File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
            cursor.execute(statement, parameters)
        sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) insert or update on table "collection" violates foreign key constraint "collection_parent_path_fkey"
        DETAIL:  Key (parent_path)=(joey.d@example.net) is not present in table "collection".
         'INSERT INTO collection (path, parent_path) VALUES (%(path)s, %(parent_path)s)' {'parent_path': 'joey.d@example.net', 'path': 'joey.d@example.net/work'}

**Comment by liZe** [comment] 2015-01-12 18:35
Duplicate of #114.

**Closed by liZe** 2015-01-12 18:35 UTC
Labels: bug
