### ISSUE TITLE
Non-ASCII passwords are not accepted on the web interface

### ISSUE THREAD

**Issue by vigiraud** [Kozea/Radicale#839] opened 2018-06-18 00:09 UTC
Non-ASCII passwords are not supported on the web interface, when authenticating. One get a «401 Unauthorized» even when entering the correct utf-8 password.

How to reproduce :
-  With **htpasswd -B -c /path/to/file user**, create a password file with an user in it. Bcrypt will be used. Put non-ASCII characters in the password, like «ç», «à», «œ» or «è» for example.
- Setup the rest of the radicale server, launch it, and go to its web page.
- Try to authenticate with the previously made account.

**htpasswd** seems to correctly handle utf-8 password, since verifying them with **htpasswd -v /path/to/file user** works. Also, clients like DAVdroid and Thunderbird actually works too. The issue probably resides in the web interface.

**Comment by DietmarSchwertberger** [comment] 2019-12-18 23:09
It's even worse: even ASCII characters are not supported when using `htpasswd_encryption = plain`.

The error message on the command line is
`ERROR: An exception occurred during GET request on '/': comparing strings with non-ASCII characters is not supported`

I am really surprised that the instructions on https://radicale.org/setup/ are more or less untested.

**Comment by prcmt** [comment] 2020-03-03 13:21
I get this error trying to use a users file of any kind - bycrypt or plain, even with purely ASCII characters.

**Comment by PinkDev1** [comment] 2020-06-08 21:30
2020-06-08. Succesfully replicated the issue with:
Radicale 3.0.0
Firefox 77.0.1 (64-bit)

How is this still an issue smh

**Comment by dragtheron** [comment] 2021-01-08 10:01
#1136 should resolve this issue.

**Comment by Jeinzi** [comment] 2023-08-06 21:12
I can't replicate this on an Arch server with:
- Python 3.11.3-2
- Radicale 3.1.8-2 or the current head d7ce2f0
- Firefox 115.0.2-1

I added a new user with the (bcrypt hashed) password "çàœè" and can use it to login to the web interface and create/delete collections. I've also been using KeepassXC "Extended ASCII" passwords since 2021-02-03 without a problem, but I'm not logging in to the webinterface that often.

**Comment by pbiering** [comment] 2024-03-01 05:09
if not reproducable, can this be closed now?

**Comment by pbiering** [comment] 2024-03-09 07:00
fixed now by https://github.com/Kozea/Radicale/pull/1136

**Closed by pbiering** 2024-03-09 07:00 UTC
Labels: bug
