### ISSUE TITLE
Windows Phone iCloud client is using authenticated user instead of given path

### ISSUE THREAD

**Issue by pbiering** [Kozea/Radicale#275] opened 2015-03-23 19:08 UTC
While fighting now for some days I hope I can get help here. Initially I've setup'ed radicale to use with Thunderbird and multiple calendars (personal, some group), working fine.

But trying to connect a Windows Phone with iCloud client causes an issue where I don't know whether it's a WP or a radicale (0.10) issue. I can't use custom paths (to use group calendars). It somehow always falls back to the authenticated user - seen on a fresh (test) setup.

Scenario: cleaned collection in radicale, radicale is set for enabling authentication, but having rights=None
New WP iCloud config with URI /test/
Start sync

According to log it tries to access /test/ (which is created then as directory by radicale - but without test.props). But then it falls back to the authenticated user and use this as URI and radicale is creating that particular user directory including the .props file

```
2015-03-23 18:50:18,027 - INFO: Starting Radicale
2015-03-23 18:50:18,047 - DEBUG: Authentication type is IMAP
2015-03-23 18:50:18,085 - DEBUG: Base URL prefix: /
2015-03-23 18:50:18,088 - DEBUG: Listening to :: port 8080
2015-03-23 18:50:18,090 - DEBUG: Radicale server ready
2015-03-23 18:50:35,770 - INFO: PROPFIND request at /test/ received
2015-03-23 18:50:35,775 - DEBUG: Request headers:
{'CONTENT_LENGTH': '111',
 'CONTENT_TYPE': 'text/xml',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_AUTHORIZATION': '***blanked***,
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_DEPTH': '0',
 'HTTP_HOST': '***blanked***,
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_USER_AGENT': 'MSFT-WP/8.10.14234 (gzip)',
 'PATH_INFO': '/test/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '***blanked***,
 'REMOTE_HOST': '***blanked***,
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '::',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.5',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fe8555041e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7fe8498c2ae0>,
 'wsgi.input': <socket._fileobject object at 0x192bed0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2015-03-23 18:50:35,779 - DEBUG: Sanitized path: /test/
2015-03-23 18:50:35,781 - DEBUG: Connecting to IMAP server imap.bieringer.de:993.
2015-03-23 18:50:36,163 - DEBUG: Authenticated IMAP user peter.bieringer via imap.bieringer.de.
2015-03-23 18:50:36,167 - DEBUG: peter.bieringer has read access to collection test/
2015-03-23 18:50:36,169 - DEBUG: peter.bieringer has write access to collection test/
2015-03-23 18:50:36,170 - DEBUG: Request content:
<?xml version="1.0" encoding="UTF-8"?><propfind xmlns="DAV:"><prop><current-user-principal /></prop></propfind>
2015-03-23 18:50:36,178 - DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:">
  <response>
    <href>/test/</href>
    <propstat>
      <prop>
        <current-user-principal>
          <href>/peter.bieringer/</href>
        </current-user-principal>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
  </response>
</multistatus>

2015-03-23 18:50:36,182 - DEBUG: Answer status: 207 Unknown
2015-03-23 18:50:36,678 - INFO: PROPFIND request at /peter.bieringer/ received
2015-03-23 18:50:36,682 - DEBUG: Request headers:
{'CONTENT_LENGTH': '144',
 'CONTENT_TYPE': 'text/xml',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_AUTHORIZATION': '***blanked***,
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_DEPTH': '0',
 'HTTP_HOST': '***blanked***,
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_USER_AGENT': 'MSFT-WP/8.10.14234 (gzip)',
 'PATH_INFO': '/peter.bieringer/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '***blanked***,
 'REMOTE_HOST': '***blanked***,
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '::',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.5',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fe8555041e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7fe8498c2ae0>,
 'wsgi.input': <socket._fileobject object at 0x192bed0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2015-03-23 18:50:36,683 - DEBUG: Sanitized path: /peter.bieringer/
2015-03-23 18:50:36,684 - DEBUG: Connecting to IMAP server imap.bieringer.de:993.
2015-03-23 18:50:37,042 - DEBUG: Authenticated IMAP user peter.bieringer via imap.bieringer.de.
2015-03-23 18:50:37,045 - DEBUG: peter.bieringer has read access to collection peter.bieringer/
2015-03-23 18:50:37,048 - DEBUG: peter.bieringer has write access to collection peter.bieringer/
2015-03-23 18:50:37,050 - DEBUG: Request content:
<?xml version="1.0" encoding="UTF-8"?><propfind xmlns="DAV:"><prop><calendar-home-set xmlns="urn:ietf:params:xml:ns:caldav" /></prop></propfind>
2015-03-23 18:50:37,053 - DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <response>
    <href>/peter.bieringer/</href>
    <propstat>
      <prop>
        <C:calendar-home-set>
          <href>/peter.bieringer/</href>
        </C:calendar-home-set>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
  </response>
</multistatus>

2015-03-23 18:50:37,054 - DEBUG: Answer status: 207 Unknown
2015-03-23 18:50:37,623 - INFO: PROPFIND request at /peter.bieringer/ received
2015-03-23 18:50:37,628 - DEBUG: Request headers:
{'CONTENT_LENGTH': '278',
 'CONTENT_TYPE': 'text/xml',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_AUTHORIZATION': '***blanked***,
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_DEPTH': '1',
 'HTTP_HOST': '***blanked***,
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_USER_AGENT': 'MSFT-WP/8.10.14234 (gzip)',
 'PATH_INFO': '/peter.bieringer/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '***blanked***,
 'REMOTE_HOST': '***blanked***,
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '::',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.5',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fe8555041e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7fe8498c2ae0>,
 'wsgi.input': <socket._fileobject object at 0x192bed0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2015-03-23 18:50:37,634 - DEBUG: Sanitized path: /peter.bieringer/
2015-03-23 18:50:37,635 - DEBUG: Connecting to IMAP server imap.bieringer.de:993.
2015-03-23 18:50:37,983 - DEBUG: Authenticated IMAP user peter.bieringer via imap.bieringer.de.
2015-03-23 18:50:37,985 - DEBUG: peter.bieringer has read access to collection peter.bieringer/
2015-03-23 18:50:37,992 - DEBUG: peter.bieringer has write access to collection peter.bieringer/
2015-03-23 18:50:37,993 - DEBUG: Request content:
<?xml version="1.0" encoding="UTF-8"?><propfind xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns="DAV:"><prop><getctag xmlns="http://calendarserver.org/ns/" /><resourcetype /><displayname /><cal:supported-calendar-data /><cal:supported-calendar-component-set /></prop></propfind>
2015-03-23 18:50:38,002 - DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://calendarserver.org/ns/">
  <response>
    <href>/peter.bieringer/</href>
    <propstat>
      <prop>
        <CS:getctag>"b51573a587c4e29d6ad3df29277c472e"</CS:getctag>
        <resourcetype>
          <principal />
          <C:calendar />
          <collection />
        </resourcetype>
        <displayname>peter.bieringer</displayname>
        <C:supported-calendar-component-set>
          <C:comp name="VTODO" />
          <C:comp name="VEVENT" />
          <C:comp name="VJOURNAL" />
        </C:supported-calendar-component-set>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
      <prop>
        <C:supported-calendar-data />
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
  </response>
</multistatus>

2015-03-23 18:50:38,007 - DEBUG: Answer status: 207 Unknown
2015-03-23 18:50:38,553 - INFO: REPORT request at /peter.bieringer/ received
2015-03-23 18:50:38,560 - DEBUG: Request headers:
{'CONTENT_LENGTH': '310',
 'CONTENT_TYPE': 'text/xml',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_AUTHORIZATION': '***blanked***,
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_DEPTH': '0',
 'HTTP_HOST': '***blanked***,
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_USER_AGENT': 'MSFT-WP/8.10.14234 (gzip)',
 'PATH_INFO': '/peter.bieringer/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '***blanked***,
 'REMOTE_HOST': '***blanked***,
 'REQUEST_METHOD': 'REPORT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '::',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.5',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fe8555041e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7fe8498c2ae0>,
 'wsgi.input': <socket._fileobject object at 0x192bed0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2015-03-23 18:50:38,564 - DEBUG: Sanitized path: /peter.bieringer/
2015-03-23 18:50:38,565 - DEBUG: Connecting to IMAP server imap.bieringer.de:993.
2015-03-23 18:50:38,908 - DEBUG: Authenticated IMAP user peter.bieringer via imap.bieringer.de.
2015-03-23 18:50:38,910 - DEBUG: peter.bieringer has read access to collection peter.bieringer/
2015-03-23 18:50:38,912 - DEBUG: peter.bieringer has write access to collection peter.bieringer/
2015-03-23 18:50:38,913 - DEBUG: Request content:
<?xml version="1.0" encoding="UTF-8"?><calendar-query xmlns="urn:ietf:params:xml:ns:caldav"><prop xmlns="DAV:"><getetag /></prop><filter><comp-filter name="VCALENDAR"><comp-filter name="VEVENT"><time-range start="20150309T000000Z" end="20150907T000000Z" /></comp-filter></comp-filter></filter></calendar-query>
2015-03-23 18:50:38,921 - DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:" />
2015-03-23 18:50:38,924 - DEBUG: Answer status: 207 Unknown
2015-03-23 18:50:39,527 - INFO: PROPFIND request at /test/ received
2015-03-23 18:50:39,530 - DEBUG: Request headers:
{'CONTENT_LENGTH': '111',
 'CONTENT_TYPE': 'text/xml',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_AUTHORIZATION': '***blanked***,
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_DEPTH': '0',
 'HTTP_HOST': '***blanked***,
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_USER_AGENT': 'MSFT-WP/8.10.14234 (gzip)',
 'PATH_INFO': '/test/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '***blanked***,
 'REMOTE_HOST': '***blanked***,
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '::',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.5',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fe8555041e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7fe8498c2ae0>,
 'wsgi.input': <socket._fileobject object at 0x192bed0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2015-03-23 18:50:39,540 - DEBUG: Sanitized path: /test/
2015-03-23 18:50:39,541 - DEBUG: Connecting to IMAP server imap.bieringer.de:993.
2015-03-23 18:50:39,893 - DEBUG: Authenticated IMAP user peter.bieringer via imap.bieringer.de.
2015-03-23 18:50:39,896 - DEBUG: peter.bieringer has read access to collection test/
2015-03-23 18:50:39,898 - DEBUG: peter.bieringer has write access to collection test/
2015-03-23 18:50:39,899 - DEBUG: Request content:
<?xml version="1.0" encoding="UTF-8"?><propfind xmlns="DAV:"><prop><current-user-principal /></prop></propfind>
2015-03-23 18:50:39,902 - DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:">
  <response>
    <href>/test/</href>
    <propstat>
      <prop>
        <current-user-principal>
          <href>/peter.bieringer/</href>
        </current-user-principal>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
  </response>
</multistatus>

2015-03-23 18:50:39,904 - DEBUG: Answer status: 207 Unknown
2015-03-23 18:50:40,361 - INFO: PROPFIND request at /peter.bieringer/ received
2015-03-23 18:50:40,367 - DEBUG: Request headers:
{'CONTENT_LENGTH': '144',
 'CONTENT_TYPE': 'text/xml',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_AUTHORIZATION': '***blanked***,
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_DEPTH': '0',
 'HTTP_HOST': '***blanked***,
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_USER_AGENT': 'MSFT-WP/8.10.14234 (gzip)',
 'PATH_INFO': '/peter.bieringer/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '***blanked***,
 'REMOTE_HOST': '***blanked***,
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '::',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.5',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fe8555041e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7fe8498c2ae0>,
 'wsgi.input': <socket._fileobject object at 0x192bed0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2015-03-23 18:50:40,369 - DEBUG: Sanitized path: /peter.bieringer/
2015-03-23 18:50:40,369 - DEBUG: Connecting to IMAP server imap.bieringer.de:993.
2015-03-23 18:50:40,709 - DEBUG: Authenticated IMAP user peter.bieringer via imap.bieringer.de.
2015-03-23 18:50:40,712 - DEBUG: peter.bieringer has read access to collection peter.bieringer/
2015-03-23 18:50:40,715 - DEBUG: peter.bieringer has write access to collection peter.bieringer/
2015-03-23 18:50:40,717 - DEBUG: Request content:
<?xml version="1.0" encoding="UTF-8"?><propfind xmlns="DAV:"><prop><calendar-home-set xmlns="urn:ietf:params:xml:ns:caldav" /></prop></propfind>
2015-03-23 18:50:40,722 - DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <response>
    <href>/peter.bieringer/</href>
    <propstat>
      <prop>
        <C:calendar-home-set>
          <href>/peter.bieringer/</href>
        </C:calendar-home-set>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
  </response>
</multistatus>

2015-03-23 18:50:40,727 - DEBUG: Answer status: 207 Unknown
2015-03-23 18:50:41,151 - INFO: PROPFIND request at /peter.bieringer/ received
2015-03-23 18:50:41,159 - DEBUG: Request headers:
{'CONTENT_LENGTH': '278',
 'CONTENT_TYPE': 'text/xml',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_AUTHORIZATION': '***blanked***,
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_DEPTH': '1',
 'HTTP_HOST': '***blanked***,
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_USER_AGENT': 'MSFT-WP/8.10.14234 (gzip)',
 'PATH_INFO': '/peter.bieringer/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '***blanked***,
 'REMOTE_HOST': '***blanked***,
 'REQUEST_METHOD': 'PROPFIND',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '::',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.5',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fe8555041e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7fe8498c2ae0>,
 'wsgi.input': <socket._fileobject object at 0x192bed0>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2015-03-23 18:50:41,164 - DEBUG: Sanitized path: /peter.bieringer/
2015-03-23 18:50:41,164 - DEBUG: Connecting to IMAP server imap.bieringer.de:993.
2015-03-23 18:50:41,512 - DEBUG: Authenticated IMAP user peter.bieringer via imap.bieringer.de.
2015-03-23 18:50:41,518 - DEBUG: peter.bieringer has read access to collection peter.bieringer/
2015-03-23 18:50:41,520 - DEBUG: peter.bieringer has write access to collection peter.bieringer/
2015-03-23 18:50:41,521 - DEBUG: Request content:
<?xml version="1.0" encoding="UTF-8"?><propfind xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns="DAV:"><prop><getctag xmlns="http://calendarserver.org/ns/" /><resourcetype /><displayname /><cal:supported-calendar-data /><cal:supported-calendar-component-set /></prop></propfind>
2015-03-23 18:50:41,524 - DEBUG: Response content:
<?xml version="1.0"?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://calendarserver.org/ns/">
  <response>
    <href>/peter.bieringer/</href>
    <propstat>
      <prop>
        <CS:getctag>"b51573a587c4e29d6ad3df29277c472e"</CS:getctag>
        <resourcetype>
          <principal />
          <C:calendar />
          <collection />
        </resourcetype>
        <displayname>peter.bieringer</displayname>
        <C:supported-calendar-component-set>
          <C:comp name="VTODO" />
          <C:comp name="VEVENT" />
          <C:comp name="VJOURNAL" />
        </C:supported-calendar-component-set>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
      <prop>
        <C:supported-calendar-data />
      </prop>
      <status>HTTP/1.1 404 Not Found</status>
    </propstat>
  </response>
</multistatus>

2015-03-23 18:50:41,530 - DEBUG: Answer status: 207 Unknown
```

**Comment by pbiering** [comment] 2015-03-24 07:49
Just as an update, after more playing around I've realized that the WP will have more automatic inside and I have now successfully created group calendars by softlinking group calendar directories and the props files into the users's folder - also no need to add additional iCal calendars, the WP will update itself on next Sync and shows all calendars now.

The base "magic" is that it looks like to be impossible to use a specified a different base path than the users's one in an URL. All has to be in the users's folder (= current-principal)

**Comment by Unrud** [comment] 2017-06-09 20:52
I close this, because It's the expected behavior. Calendar sharing is not (yet) supported by Radicale.

**Closed by Unrud** 2017-06-09 20:52 UTC
Labels: bug
