### ISSUE TITLE
sqlalchemy errors

### ISSUE THREAD

**Issue by somecallmemike** [Kozea/Radicale#244] opened 2014-12-18 20:30 UTC
Seeing the following error while attempting to add something to a calendar.

PUT request at /user@domain.net/calendar.ics/20141218T142520Z-bRM6JAP.ics received
Traceback (most recent call last):
  File "/usr/lib64/python2.6/wsgiref/handlers.py", line 93, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python2.6/site-packages/radicale/__init__.py", line 306, in __call__
    user)
  File "/usr/lib/python2.6/site-packages/radicale/__init__.py", line 565, in put
    new_item = collection.get_item(item_name)
  File "/usr/lib/python2.6/site-packages/radicale/ical.py", line 354, in get_item
    for item in self.items:
  File "/usr/lib/python2.6/site-packages/radicale/storage/database.py", line 264, in items
    (ical.Event, ical.Todo, ical.Journal, ical.Card, ical.Timezone))
  File "/usr/lib/python2.6/site-packages/radicale/storage/database.py", line 119, in _query
    .order_by(DBItem.name).all())
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2320, in all
    return list(self)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2437, in __iter__
    self.session._autoflush()
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1208, in _autoflush
    util.raise_from_cause(e)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1198, in _autoflush
    self.flush()
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/persistence.py", line 570, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.6/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 928, in _execute_context
    context)
  File "/usr/lib/python2.6/site-packages/sqlalchemy/connectors/mysqldb.py", line 68, in do_executemany
    rowcount = cursor.executemany(statement, parameters)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py", line 205, in executemany
    r = r + self.execute(query, a)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py", line 173, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) (1062, "Duplicate entry 'America/Chicago' for key 'PRIMARY'") 'INSERT INTO item (name, tag, collection_path) VALUES (%s, %s, %s)' (('America/Chicago', 'VTIMEZONE', 'user@domain.net/calendar.ics'), ('20141218T142520Z-bRM6JAP.ics', 'VEVENT', 'user@domain.net/calendar.ics'))
Exception sqlalchemy.exc.InvalidRequestError: InvalidRequestError('This Session\'s transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) (1062, "Duplicate entry \'America/Chicago\' for key \'PRIMARY\'") \'INSERT INTO item (name, tag, collection_path) VALUES (%s, %s, %s)\' ((\'America/Chicago\', \'VTIMEZONE\', \'user@domain.net/calendar.ics\'), (\'20141218T142520Z-bRM6JAP.ics\', \'VEVENT\', \'user@domain.net/calendar.ics\'))',) in <bound method Collection.__del__ of <radicale.storage.database.Collection object at 0x7fbeb0383790>> ignored

**Comment by liZe** [comment] 2015-01-12 18:35
Duplicate of #114.

**Closed by liZe** 2015-01-12 18:35 UTC
